### ISSUE TITLE
rv64ui-p-sd : The simulation success , but .data contents didn't change.

### ISSUE THREAD

**Issue by kelayamatoz** [chipsalliance/rocket-chip#1013]
I have done following test:
  cd vsim
  make output/rv64ui-p-sw.vpd
  make output/rv64ui-p-sd.vpd

when checking the rv64ui-p-sw.vpd, the .data contents changed as expected.
but when checking the rv64ui-p-sd.vpd, the .data contents didn't change.

**Comment by aswaterman** [comment]
If you think you've observed a bug, can you propose a test that exposes it? It sounds like you're misunderstanding the micro architecture.

**Comment by kelayamatoz** [comment]
![2017-09-22 6 54 28](https://user-images.githubusercontent.com/1896351/30741817-01e06908-9fc9-11e7-8779-997e5f5484c7.png)
![2017-09-22 6 52 45](https://user-images.githubusercontent.com/1896351/30741816-01e047e8-9fc9-11e7-92ed-6a1731c2d9b2.png)

**Comment by aswaterman** [comment]
I stand by my original question

**Comment by kelayamatoz** [comment]
Yes, I just start to understanding the micro architecture. I am thinking either of them should have similar behavior. 
sorry for my poor english. for your first question, I know every word but can't understand it. Do you want detail steps to show the problem?

**Comment by mwachs5** [comment]
@kelayamatoz , I think what @aswaterman is asking is:

1) What exact test did you run? What configuration and what test? (I think you answered that above)

2) What did you expect to happen?

3) What actually happened, and how is that different from what you expected to happen?

In your original question, you said "the .data contents changed as expected". Not sure exactly what you mean "as expected", can you be more clear?
