### ISSUE TITLE
how compile test for core with  FPU without div and sqtr 

### ISSUE THREAD

**Issue by esolera** [chipsalliance/rocket-chip#1026]
I have the next question. When I compile I use -march=rv64imafd . This option in compilation  includes all floatpoint instrucction includes fsqrt.s, fsqrt.d, f.div.s and fdiv.d. This four instrucction aren't supported by the FPU. I create this core. What kind of -march=? can I use to compile intrucctions with this FPU : 

  class Default64conFPUsindivsinsqtrsinC extends Config( new WithFPUWithoutDivSqrt ++ new WithoutCompressed ++ new DefaultConfig )

**Comment by ccelio** [comment]
Using `riscv64-unknown-elf-gcc --help=target` will point you to `-mfdiv: Use hardware floating-point divide and square root instructions.` So `mno-fdiv` should do the trick.
