### ISSUE TITLE
Build the C simulator  Issue

### ISSUE THREAD

**Issue by riscveval** [chipsalliance/rocket-chip#1028]
Hi when i am trying to build the C simulator in emulator folder i am getting the following sbt compilation issue  

/home/krradhak/Free-chip_project/rocket-chip/chisel3/build.sbt:142: warning: `<++=` operator is deprecated. Try `lhs ++= { x.value }`
  or see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html.
    mappings in (Compile, packageSrc) <++= mappings in (chiselFrontend, Compile, packageSrc),
                                      ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by Kallil12** [comment]
Hi, did you solve the problem?
