### ISSUE TITLE
What's the algorithm of scoreboard unit?

### ISSUE THREAD

**Issue by Ddnirvana** [chipsalliance/rocket-chip#1056]
Hi, guys,

I am reading the codes of Rocket-chip. And when I read the Rocket Core part, I find that Rocket-chip uses scoreboarding to help to detect the data hazards in pipeline. However,  I find that the implementation of this Scoreboard unit seems not matching what I have learned....

The module of Scoreboard is the following:
```scala
 class Scoreboard(n: Int)
  {
    def set(en: Bool, addr: UInt): Unit = update(en, _next | mask(en, addr))
    def clear(en: Bool, addr: UInt): Unit = update(en, _next & ~mask(en, addr))
    def read(addr: UInt): Bool = r(addr)
    def readBypassed(addr: UInt): Bool = _next(addr)

    private val r = Reg(init=Bits(0, n))
    private var _next = r
    private var ens = Bool(false)
    private def mask(en: Bool, addr: UInt) = Mux(en, UInt(1) << addr, UInt(0))
    private def update(en: Bool, update: UInt) = {
      _next = update
      ens = ens || en
      when (ens) { r := _next }
    }
  }
```
And what I have learned is that: Scoreboard first records all instructions, checking the FUs' status,issue an instruction, and so on...

So, my question is that what's the algorithm of scoreboarding in Rocket-chip?
Any advices are welcomed? Thanks a lot!

**Comment by sequencer** [comment]
This need the uarch documentation. closing for now, which will be gathered to the documentation road map.
