### ISSUE TITLE
How to test the implementation module with leverage utility as tilelink?

### ISSUE THREAD

**Issue by nnamenoname** [chipsalliance/rocket-chip#1185]
Hi, 
Sorry I am not familiar with rocket chip utility utilization.
I implement an accelerator written in Chisel and wrap it as tilelink master interface follow blockdevice.scala(in ucb-bar/testchipip).
I want to test whether is it correct for the functionality, however, it is not wise to test it with writing c program and rocket chip emulator due to long simulation time.
I want to ask are there the other alternative to complete testing. I have not found any document about it therefore I have no idea about it.

Another question, can I utilize peek poke function to the the module wrapped with the tilelink utility(e.g
(tl, edge) = outer.node.out(0) )

**Comment by codelec** [comment]
@nnamenoname you can try something like this 
```scala 
class Top extends Module {
  val inParams = new WithAdapterParameters
  val tile = LazyModule(new Tile()(inParams)).module
  val io = IO(new Bundle {
    val mem_axi = tile.mem_axi4.cloneType
  })
  io.mem_axi <> tile.mem_axi4
}
```
use peek poke on module `Top` and your module `Tile` containing the tilelink utility
