### ISSUE TITLE
Output files are not generated

### ISSUE THREAD

**Issue by tariqazmy** [chipsalliance/rocket-chip#1188]
I did follow all the steps to generate the Rocket Core emulator and run the assembly and benchmark tests. 

$ cd $ROCKETCHIP/emulator
$ make -jN run (assuming N is # of core)

make finished without any errors, but I did not see any output files inside output folder in the emulator directory. The only files that are generated are the link-to-executable type of files.

In addition, there is no freechips.rocketchip.system.DefaultConfig folder inside emulator/generated-src directory. This is the folder that contains VTestHarness cpp files.

Any thoughts?

Thanks

**Comment by michael-etzkorn** [comment]
This is a relatively old issue and there's not enough information to replicate. I'll go ahead and close this. If you feel this still needs to be addressed with today's `master` branch, please provide more information about your environment when you reopen.
