### ISSUE TITLE
Icache

### ISSUE THREAD

**Issue by zhanghongyuanvg** [chipsalliance/rocket-chip#1264]
Hello,
Could you tell me why rocket can not work without Icache?
Can I design a simple mechanism to replace Icache? If so, what should I do?
Thanks.

**Comment by michael-etzkorn** [comment]
Frontend instantiates ICache. You would have to surgically remove it from the code or do serious refactoring to parameterize it away entirely. 

Feel free to repost on StackOverflow if you'd like to follow up this question further.
