### ISSUE TITLE
Error while run "make" in /vsim

### ISSUE THREAD

**Issue by WX10** [chipsalliance/rocket-chip#1391]
make[1]: Entering directory '/home/david/rocket-chip/vsim/csrc'
make[1]: Leaving directory '/home/david/rocket-chip/vsim/csrc'
make[1]: Entering directory '/home/david/rocket-chip/vsim/csrc'
g++ -w  -pipe -fPIC -I/opt/synopsys/vcs/include -I/home/david/riscv-tools/include -std=c++11 -Wl,-rpath,/home/david/riscv-tools/lib -O -I/opt/synopsys/vcs/include    -c /home/david/rocket-chip/src/main/resources/csrc//SimDTM.cc
g++ -w  -pipe -fPIC -I/opt/synopsys/vcs/include -I/home/david/riscv-tools/include -std=c++11 -Wl,-rpath,/home/david/riscv-tools/lib -O -I/opt/synopsys/vcs/include    -c /home/david/rocket-chip/src/main/resources/csrc//SimJTAG.cc
g++ -w  -pipe -fPIC -I/opt/synopsys/vcs/include -I/home/david/riscv-tools/include -std=c++11 -Wl,-rpath,/home/david/riscv-tools/lib -O -I/opt/synopsys/vcs/include    -c /home/david/rocket-chip/src/main/resources/csrc//remote_bitbang.cc
cc1: warning: command line option '-std=c++11' is valid for C++/ObjC++ but not for C
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCheckCallocFromGroupFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsSetSmallCaching'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `initNativeUcli'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsGroupSize'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `storeMiscTfCb'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsHighMemory'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsStrdupFunc'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `setIclCmd_ResVars'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `shutDownNativeUcli'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCallocFromGroup'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `isUcliEngineStarted'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCheckStrdupFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsFreeFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsNamedPopGroup'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsGroupGetActive'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `registerOutOfMemHandle'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsFreeGroup'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsNamedPushGroup'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCheckFreeFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsSetHook'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `printIclBeginMarker'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `setEnvPair'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCheckReallocFunc'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `storeSimLogFileHandle'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `waitForUserInput'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `execMhpiTclCommand'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `miHeapProf_init'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCheckCallocFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snps__StrdupFunc'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `registerPreRestartFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsMallocFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsMallocFromGroup'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsPrintf'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsSetOutOfMemoryRoutine'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `executeTclProc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsMemSetLogFileHandle'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `miHeapOn'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCheckMallocFunc'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `printIclEndMarker'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `vcsRunUcliErrorScript'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsDoStackUnwind'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `execMhpiTclCommandNoPrint'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCallocFunc'
/opt/synopsys/vcs/linux64/lib/libvcsucli.so: undefined reference to `breakNativeTclLoop'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsMemManagerIsActive'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsGetHook'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCheckMallocFromGroupFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsReallocFunc'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsReallocFromGroup'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsGetMemBytes'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsNamedAllocateGroup'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsLowMemory'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsCurrentGroup'
/opt/synopsys/vcs/linux64/lib/libvcsnew.so: undefined reference to `snpsOutOfMem'
collect2: error: ld returned 1 exit status
Makefile:104: recipe for target 'product_timestamp' failed
make[1]: *** [product_timestamp] Error 1
make[1]: Leaving directory '/home/david/rocket-chip/vsim/csrc'
Make exited with status 2
Makefrag:66: recipe for target 'simv-freechips.rocketchip.system-DefaultConfig' failed
make: *** [simv-freechips.rocketchip.system-DefaultConfig] Error 2

**Comment by sequencer** [comment]
not reproducible error with unknown environment.
Close this issue, if any further question feel free to reopen.
