### ISSUE TITLE
Simulate the RTL with Questa

### ISSUE THREAD

**Issue by mohit162009** [chipsalliance/rocket-chip#1437]
Hello,

I am new to rocketchip. I am able to set up everything and also able to dump the RTL into _vsim_ directory. Now I want to simulate it with Questa. Is there some way to do so? 

Thanks.

**Comment by YoussefZakari** [comment]
@mohit162009 Have you made progress with QuestaSIM ? My problem is the run command line, and I think I need to pass an ELF binary using vsim command.
