### ISSUE TITLE
unable to build riscv-tools

### ISSUE THREAD

**Issue by pa1ly** [chipsalliance/rocket-chip#1456]
Starting RISC-V Toolchain build process

libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
configure.ac:12: error: possibly undefined macro: AC_MSG_WARN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:205: error: possibly undefined macro: AC_DEFINE
configure.ac:609: error: possibly undefined macro: AC_MSG_NOTICE
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by mayoru** [comment]
Try updating aclocal, automake (up to 1.14).
Also, what's your version of libtool?
Check if you have installed all the needed dependencies: https://github.com/riscv/riscv-tools/blob/priv-1.10/README.md#quickstart
