### ISSUE TITLE
rocket will supports DSP (P) ISA extension and Vector (V) ISA extension?

### ISSUE THREAD

**Issue by Xuwmzzz** [chipsalliance/rocket-chip#1491]
Dear all,

I know from the 8th RISC-V workshop that the DSP (P) ISA extension is proposed and the Vector (V) ISA extension is designing now. What I want to know is that if rocket will updates to supprot the  DSP (P) ISA extension and the Vector (V) ISA extension, when P and V extension are freezing?

Thank you!

**Comment by aswaterman** [comment]
V support is likely. P support is less likely, but it’s not out of the question. I can’t offer a timeline on either yet, since the ISAs aren’t frozen.

**Comment by aswaterman** [comment]
@colinschmidt

**Comment by colinschmidt** [comment]
We plan to make a final public release of Hwacha in the early fall.
