### ISSUE TITLE
What's the purpose of link the RISC-V programs to 0x8000_0000?

### ISSUE THREAD

**Issue by clx7913** [chipsalliance/rocket-chip#1510]
If I don't do that, it seems that the riscv64-unknown-elf-gdb couldn't "load" the programs like the README file says : https://github.com/freechipsproject/rocket-chip#5-launch-gdb

**Comment by clx7913** [comment]
Isn't "0x8000_0000" the start point of RAM? I am a rookie and puzzled.

Any suggestions would be appreciated.

**Comment by CLappin** [comment]
0x8000_0000 is the starting address of the cached interface. In the default config I believe it goes to 0x9000_0000.
