### ISSUE TITLE
How to write custom benchmarks to run on rocket chip?

### ISSUE THREAD

**Issue by pa1ly** [chipsalliance/rocket-chip#1557]

**Comment by Ssavas** [comment]
For bare-metal programs: 
You can use the startup code, linker files and syscall files from riscv-tests. They are in the directory called common (rocketchip\riscv-tools\riscv-tests\benchmarks). You can also take a look at the benchmarks to see how to use some system calls (such as setStats() which measures the number of cycles).  You can copy the makefile and modify it to compile your custom benchmark. Then you can run your executable on an emulator that you generate in the emulator folder of rocketchip.
