### ISSUE TITLE
A question about front_port.

### ISSUE THREAD

**Issue by Xuwmzzz** [chipsalliance/rocket-chip#1567]
Dear all,

I know front_port can read/write DTIM and ITIM.
Also it can read D-Cache.
but can it write D-Cache?

Thank you!

**Comment by aswaterman** [comment]
The front port can communicate coherently with the D$, but it doesn't access the D$ directly.  Instead, it goes through the cache-coherence subsystem, which will send invalidation messages to the D$ if necessary.

**Comment by Xuwmzzz** [comment]
Yes, i know the front port don't access the D$ directly.
It can use TileLink(TL-UH) to access subsystem to read the data in D$(send invalidation messages to the D$ and make the data wirteback). 
My question is that can the front port write new data to D$ by accessing subsystem?
Can the front port use 0 opcode(TileLink)  to write data when i use D$? 
Or can the front port only use 4 opcode(TileLink)  to read data when i use D$?
Thank you!

**Comment by aswaterman** [comment]
Yes, you can issue writes over the front port, and they will be coherent with the D$.

**Comment by Xuwmzzz** [comment]
Ok, i see. 
Thank you very much!

**Comment by hcook** [comment]
Yes, in order to read the value that was written to backing memory, the cache must read from backing memory.
