### ISSUE TITLE
running the rocket chip without a fesvr

### ISSUE THREAD

**Issue by rgaehfgoiarewhg** [chipsalliance/rocket-chip#1593]
hello.

what happens when the cpu is used without a fesvr? does it still read instructions from memory or is it waiting for some input from the fesvr first?

**Comment by mwachs5** [comment]
The CPU just starts executing from whetever its reset vector is. So if you are able to load instructions to that memory/interface model in some way, then you don't need FESVR to load the code. Currently FESVR interrupts it with the debugger, loads your executable with the debugger, and then uses the debugger to set the core's PC to whatever the _start label is in the executable.
