### ISSUE TITLE
Dcache flush on FENCE.I : only supported for execuable 

### ISSUE THREAD

**Issue by ShuyunJia** [chipsalliance/rocket-chip#1610]
https://github.com/freechipsproject/rocket-chip/blob/07799f8fd536ccecbfba16760f1d9b1742184c11/src/main/scala/rocket/DCache.scala#L777

In commit `83875e3a`, I noticed the Dcache flush is only supported when Icache miss won't be able to probe modifications inside the Dcache, which is common in some self-modification program. 

For general purpose Dcache flush, however, I don't see any methods to invalidate or flush a cacheline. In system where there are processors or DMAs outside the shareable domain, a FENCE.I operation may be necessary. 

Moreover, when Mode change happens, for example, changing from machine mode into user mode, a cache flush would be much more secure. Just like what we usually do in BL31/BL32. 

I suggest that when there is any regions typed as UNCACHEABLE(which means may spontaneously change contents, as defined in object RegionType), Dcache should be able to flush or invalidate itself.

**Comment by aswaterman** [comment]
This state machine is only used to implement the FENCE.I instruction.  It's not meant to serve other purposes.

Re: DMA, we only support coherent DMA.

Re: security concerns, yes, I agree a cache-flush primitive would be useful in some circumstances.
