### ISSUE TITLE
Diplomatic Address Decoder

### ISSUE THREAD

**Issue by tampler** [chipsalliance/rocket-chip#1668]
Could anybody briefly explain how AddressDecoder works from the /diplomacy folder? I see it is actively used in several places, but I don't understand the code.

Normally, I'd instantiate AddrDecoder and provide a map of base addr and range sizes for each memory region. AD gets some address on input and provides a 1-hot region selector, based solely on initial config and input address.

That's what I'd expect to get from this one. Could anybody provide some explanations and a simple usage example?

Thank you!

**Comment by terpstra** [comment]
What you expect is indeed what the TileLink crossbar does. However, the AddressDecoder is perhaps poorly named. What it does is take sets of sets of addresses and determine the minimum number of address bits which need to be inspected to decide to which set of addresses an address belongs.

**Comment by tampler** [comment]
Thanks for your explanation. I still need a "classical" Addr Decoder. Is there any available implementation in Chisel or I should reinvent my own ?

**Comment by terpstra** [comment]
It's implemented in one line here:
https://github.com/freechipsproject/rocket-chip/blob/master/src/main/scala/tilelink/Xbar.scala#L217

**Comment by tampler** [comment]
@terpstra I disagree with your statement. What you're referring to is kind of a "Port mapper", since the **contains** method for **Map** returns true only if the key is present. Here's a simple example below:
```scala
  import collection.mutable.{Map => MMap}
  val mmap = MMap[BigInt, BigInt]()
  mmap(BigInt(0x200)) = BigInt(0x100)
  mmap(BigInt(0x300)) = BigInt(0x100)

  for ((k,v) <- mmap) 
    println(s"Base = $k, Size = $v")

  val found0  = mmap contains (0x300)
  val found1  = mmap contains (0x250)
  println (s"found0 = $found0, found1 = $found1")
```
Which prints found0 = true, found1 = false.

What I need is to implement an **inside** method, which checks address inclusion. Here's my code below
```scala
  def inside (base:BigInt, size:BigInt)(addr:BigInt = 0x0):Boolean = addr >= base && addr < base + size
  val found2  = mmap map(inside) reduce (_ || _)
```
However, this won't compile, giving the following error: type mismatch
[error]  found   : (BigInt, BigInt) => BigInt => Boolean
[error]  required: ((BigInt, BigInt)) => ?

How can I make this working ?

Thank you!

**Comment by terpstra** [comment]
The line I pointed to does do what you ask:
route_addrs.map(seq => (addr: UInt) => seq.map(_.contains(addr)).reduce(_ || _))

The _.contains(addr) is creating hardware that checks if the addr UInt is contained in an AddressSet. Then it takes all of the AddressSets for that port and ORs them together using reduce. Finally, it has the outer map which creates that hardware for each port (route_addrs is a Seq[Seq[AddressSet]].

**Comment by tampler** [comment]
@terpstra Can you show a simpler example, using only basic types and plug some numbers like I did, instead of using a context based code? Thanks

**Comment by tampler** [comment]
For the benefit of Chisel newcomers, showing my current implementation. In a pure Scala implementation, addr range is a Seq of Tuples and I apply a curried function **inside** to it:
```scala
  def inside (range:(BigInt,BigInt))(addr:BigInt):Boolean = {
      addr >= range._1 && addr < range._1 + range._2
  }

  val addr    = BigInt(0x220)
  val found0  = mmap contains (addr)
  val found1  = mmap map(inside(_)(addr)) //reduce (_ || _)
  println (s"found0 = $found0, found1 = $found1")
```
which prints: found0 = false, found1 = List(true, false)

**Comment by tampler** [comment]
However, deploying my fancy method inside a HW class yields in a type error. 
Could anyone help me to fix this ? Thank you!
```scala
class AddrDecoder[T<:UInt] (dType:T, n:Int) extends Module {
  val io = IO (new Bundle {
    //val range = (Vec(Seq.fill(n){(dType,dType)})) // This won't compile, how to fix ?
    val range = (List.fill(n){(dType,dType)})    
    val addr  = Input (dType)
    val en    = Input (Bool())    
    val sel   = Output(Bool())
  })
  
  def inside (range:(T,T))(addr:T):Bool = {
    addr >= range._1 && addr < range._1 + range._2
  }
  when (io.en) {
    io.sel := io.range map (inside(_)(io.addr))
  }
}
```
[error]  found   : List[chisel3.Bool]
[error]     (which expands to)  List[chisel3.core.Bool]
[error]  required: chisel3.core.Data
[error]     io.sel := io.range map (inside(_)(io.addr))

**Comment by tampler** [comment]
1. Now it complains on the function implementation. I purposely moved the logical op to the function to see how it works.
```scala
  def inside (range:(T,T))(addr:T):Bool = {
    addr >= range._1 && addr < range._1 + range._2 // < --- here
  }
```
  chisel3.core.Binding$ExpectedHardwareException: bits operated on 'chisel3.core.UInt@cfd1602' must be hardware, not a bare Chisel type. Perhaps you forgot to wrap it in Wire(_) or IO(_)?

2. If I wanted to use 
```scala
class AddrDecoder[T<:UInt] (dType:T, n:Int) extends Module {
  val io = IO (new Bundle {
    val range = Input(Vec(Seq.fill(n){(dType,dType)})) // This won't compile, how to fix ?
...
```
I'd get the following compile error:
Error: overloaded method value apply with alternatives:
[error]   [T <: chisel3.Data](elt0: T, elts: T*)chisel3.Vec[T] <and>
[error]   [T <: chisel3.Data](elts: Seq[T])chisel3.Vec[T]
[error]  cannot be applied to (Seq[(T, T)])

How to fix those issues? Thank you, Jack

**Comment by jackkoenig** [comment]
An important distinction is that between Chisel **Types** (which you can think of as like a template) and actual hardware **Values**

Since `range` is part of `io`, it needs to be a **type**.
`Vec(Seq.fill ...)` creates a value (note that you should use `VecInit` instead of `Vec` here, the reason for that is to make it more clear that it's a value)
`Vec` **types** are created with `Vec(size, type)`.

Another problem that we'll have to fix here is that currently, you cannot create chisel types nor hardware out of Tuples (eg. `(dType, dType)`), so we're going to have to create two parallel Vecs for now:
```scala
class AddrDecoder[T<:UInt] (dType:T, n:Int) extends Module {
  val io = IO (new Bundle {
    val range0 = Input(Vec(n, dType))  // <-------------- Look here
    val range1 = Input(Vec(n, dType))
    val addr  = Input (dType)
    val en    = Input (Bool())
    val sel   = Output(Bool())                                                                                                                                                                                                                                                                                              
  })

  def inside (range:(T,T))(addr:T):Bool = {
    addr >= range._1 && addr < range._1 + range._2
  }
  io.sel := false.B // Need an initial value for io.sel
  when (io.en) {
    // Now to get the tuples to pass to inside, we can zip!
    io.sel := io.range0.zip(io.range1).map(inside(_)(io.addr)).reduce(_ || _) <----- Look here
    // I'm not sure if io.sel should be a Vec of Bool or just a Bool
    // I did an or reduce which makes it true if the addr is in any of the ranges
  }
}

**Comment by tampler** [comment]
Thanks, Jack. Below is my final implementation, which I'll use in a production project. I think this is an excellent example for the next release of the Advanced Chisel Manual. This code contains lots of points to think about for beginners and I'm happy I have passed them. Thanks everybody for the help!
```scala
class AddrDecoder[T<:Data with Num[T]] (dType:T, n:Int) extends Module {
  val io = IO (new Bundle {
    val range0  = Input (Vec(n,dType))
    val range1  = Input (Vec(n,dType))    
    val addr    = Input (dType)
    val en      = Input (Bool())    
    val sel     = Output(Vec(n,Bool()))
  }) 
  // Curried function which accepts a tuple and an input addr
  // Use map to apply it to inputs
  def inside (range:(T,T))(addr:T):Bool = {
    addr >= range._1 && addr < range._1 + range._2
  }
  // MUX output
  for (i <- 0 until n) {
    io.sel(i) := false.B
  }  
  when (io.en) {
    io.sel := io.range0 zip io.range1 map (inside(_)(io.addr))
  }
  // $onehot0 output encoding check
  assert (PopCount(io.sel) <= 1.U, "Invalid addr decoding")
}

```
