### ISSUE TITLE
Cross build with Scala 2.11 is broken

### ISSUE THREAD

**Issue by Partmedia** [chipsalliance/rocket-chip#1709]
**Type of issue**: bug report

**Impact**: unknown

**Development Phase**: request

**Other information**
 

build.sbt claims to support 2.11.12 in crossScalaVersions, but the build fails. Request to fix the issue, or remove 2.11.12 from supported crossScalaVersions.

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
$ sbt
> ++ 2.11.12
> publishLocal

snip

[error] /tools/projects/kevinz/hydra-serdes/project-template/rocket-chip/src/main/scala/devices/tilelink
/DevNull.scala:55:2: ':' expected but eof found.                                                        
[error] }                                                                                               
[error]  ^        

**Please tell us about your environment:**
$ git describe --always
e627d93

$ uname -a
Linux bwrcrdsl-6 2.6.32-754.6.3.el6.x86_64 #1 SMP Tue Sep 18 10:29:08 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by michael-etzkorn** [comment]
This is no longer an issue as of the recent versions with `build.sbt` which AFAIW is currently not supporting cross-compilation anywhere.
