### ISSUE TITLE
emulator make problem 

### ISSUE THREAD

**Issue by oioeic** [chipsalliance/rocket-chip#1721]
yyj@ubuntu:~/project-template/rocket-chip$ cd emulator/
yyj@ubuntu:~/project-template/rocket-chip/emulator$ make
make -C /home/yyj/project-template/rocket-chip/firrtl SBT="java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /home/yyj/project-template/rocket-chip/sbt-launch.jar ++2.12.4" root_dir=/home/yyj/project-template/rocket-chip/firrtl build-scala
make[1]: Entering directory '/home/yyj/project-template/rocket-chip/firrtl'
java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /home/yyj/project-template/rocket-chip/sbt-launch.jar ++2.12.4 "assembly"
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/yyj/.sbt/1.0/staging/d6ccfd4d20a7dffb56d4/firrtl/project
[error] java.io.IOException: Permission denied, file: /root/.ivy2/cache/scala_2.12/sbt_1.0/com.typesafe.sbt/sbt-ghpages/jars/sbt-ghpages-0.6.2.jar
[error] 	at sbt.internal.io.MilliPosixBase.checkedIO(Milli.scala:100)
[error] 	at sbt.internal.io.Linux64Milli$.getModifiedTimeNative(Milli.scala:209)
[error] 	at sbt.internal.io.Linux64Milli$.getModifiedTimeNative(Milli.scala:204)
[error] 	at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:67)
[error] 	at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:376)
[error] 	at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error] 	at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$fileUptodate$1(LibraryManagement.scala:130)
[error] 	at scala.runtime.java8.JFunction1$mcZJ$sp.apply(JFunction1$mcZJ$sp.java:12)
[error] 	at scala.Option.forall(Option.scala:247)
[error] 	at sbt.internal.LibraryManagement$.fileUptodate(LibraryManagement.scala:130)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$9(LibraryManagement.scala:75)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$9$adapted(LibraryManagement.scala:75)
[error] 	at scala.collection.Iterator.forall(Iterator.scala:941)
[error] 	at scala.collection.Iterator.forall$(Iterator.scala:939)
[error] 	at scala.collection.AbstractIterator.forall(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.forall(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.forall$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.forall(Iterable.scala:54)
[error] 	at sbt.internal.LibraryManagement$.upToDate$1(LibraryManagement.scala:75)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:98)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2383)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) java.io.IOException: Permission denied, file: /root/.ivy2/cache/scala_2.12/sbt_1.0/com.typesafe.sbt/sbt-ghpages/jars/sbt-ghpages-0.6.2.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] java.lang.RuntimeException: Session not initialized.
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.Project$.$anonfun$getOrError$1(Project.scala:396)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at sbt.Project$.getOrError(Project.scala:396)
[error] 	at sbt.Project$.session(Project.scala:402)
[error] 	at sbt.Project$.extract(Project.scala:407)
[error] 	at sbt.BuiltinCommands$.notifyUsersAboutShell(Main.scala:807)
[error] 	at sbt.BuiltinCommands$.$anonfun$notifyUsersAboutShell$3(Main.scala:816)
[error] 	at sbt.Command$.$anonfun$command$2(Command.scala:88)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Session not initialized.
[error] Use 'last' for the full log.
Makefile:25: recipe for target '/home/yyj/project-template/rocket-chip/firrtl/utils/bin/firrtl.jar' failed
make[1]: *** [/home/yyj/project-template/rocket-chip/firrtl/utils/bin/firrtl.jar] Error 1
make[1]: Leaving directory '/home/yyj/project-template/rocket-chip/firrtl'
/home/yyj/project-template/rocket-chip/Makefrag:28: recipe for target '/home/yyj/project-template/rocket-chip/firrtl/utils/bin/firrtl.jar' failed
make: *** [/home/yyj/project-template/rocket-chip/firrtl/utils/bin/firrtl.jar] Error 2

my .sbt and .ivy2 directory both in the /home/yyj, but the build program want find .ivy2 in the /root/.ivy2 directory, why?

**Comment by michael-etzkorn** [comment]
Seems to be a permission issue in your environment. Perhaps you installed with sudo.
