### ISSUE TITLE
Is it possible to configure DTIM  cacheable?

### ISSUE THREAD

**Issue by jimmysitu** [chipsalliance/rocket-chip#1777]
Hi, All

I trying to configure my rocket-core with DTIM as the only RAM in whole system.
However, It seems DTIM is not cacheable by ICache from the generated address map,
I guess it may lost some performance when executing code from DTIM.
Is there any way to make dtim cacheable by ICache? Thanks

```bash
Generated Address Map
	       0 -     1000 ARWX  debug-controller@0
	    3000 -     4000 ARWX  error-device@3000
	   10000 -    20000  R X  rom@10000
	 2000000 -  2010000 ARW   clint@2000000
	 c000000 - 10000000 ARW   interrupt-controller@c000000
	10012000 - 10013000 ARW   gpio@10012000
	10013000 - 10014000 ARW   gpio@10013000
	80000000 - 80004000 ARWX  dtim@80000000
```

**Comment by KevinLT8888** [comment]
If you are using default e300artyboard configs. Then this dtim plays the role as L1 dcache and can not be cached by icache.
I think you can hook a dtim to the mbus as a system level device, then it can be cached by both.
