### ISSUE TITLE
Can I instantiate a TLToAXI module by modifing Scala ?

### ISSUE THREAD

**Issue by AMing922** [chipsalliance/rocket-chip#1863]
The output of the module rocket is in TL protocol. Can I instantiate a module TLToAXI to convert the output from Tilelink to AXI4?
![96d8f912-2f44-11e7-926e-d74772c770fc](https://user-images.githubusercontent.com/38391295/53862424-5293e280-4022-11e9-9d94-277e2d0c71af.PNG)

**Comment by michael-etzkorn** [comment]
Yes.
