### ISSUE TITLE
BTB's updatesOutOfOrder: entry update index seems not correct when hit

### ISSUE THREAD

**Issue by zhouqinghua** [chipsalliance/rocket-chip#1902]
**Type of issue**: other enhancement

**Impact**: unknown

**Development Phase**: proposal

**Other information**
 
 In order to improve the performance of BTB, I configure BTB.updatesOutOfOrder to True. But I found the BTB update behavior is different from my expect.
updateHitAddr signal seems not correct when BTB.updatesOutOfOrder is True.
Are there any known bugs for this parameter?

code location(BTB.scala):
  val (updateHit, updateHitAddr) =
    if (updatesOutOfOrder) {
      val updateHits = (pageHit << 1)(Mux1H(idxMatch(r_btb_update.bits.pc), idxPages))
      (updateHits.orR, OHToUInt(updateHits))

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

**Comment by lycfly** [comment]
@zhouqinghua 
Hi~  I have the same problem. Do you know the answer, since you have closed this issue.
