### ISSUE TITLE
Attempt to access of a non-standard CSR (0x7c1) does not raise illegal instruction exception

### ISSUE THREAD

**Issue by ntuszynski** [chipsalliance/rocket-chip#1949]
**Type of issue**: bug report | other enhancement

**Impact**: API modification | unknown

**Development Phase**: request | proposal

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
For example instruction CSRRSI, with csr field set to 0x7c1

**What is the current behavior?**
The exception is not raised and returned value is '0. The question is if it is supposed to implement some additional behavior?

**What is the expected behavior?**
Expected to raise an illegal instruction exception, as 2.1 section in CSR address mapping conventions states: "Attempts to access a non-existent CSR raise an illegal instruction exception. Attempts to access a CSR without appropriate privilege level or to write a read-only register also raise illegal instruction exceptions."

**Please tell us about your environment:**

The issue is identified with OneSpin tool, 2019.1.2

**What is the use case for changing the behavior?**

**Comment by mwachs5** [comment]
This is a custom register as allowed by the ISA. It is an existing CSR.
