### ISSUE TITLE
How to use readmemh function in verilator simulation to load programs?

### ISSUE THREAD

**Issue by hyf6661669** [chipsalliance/rocket-chip#1997]
I find that the it would take lots of time to load the user codes/data into the DRAM in verilator simulation, which is controlled by the DTM. If I just want to test whether the core itself could run my codes correctly, it would save some time if I can use ```readmemh``` function to load my codes/data into the DRAM.

**Comment by Wonicon** [comment]
Add this option to FIRRTL and you can use your custom mem module which utilizes `$readmemh`.
```
  -frsq, --repl-seq-mem -c:<circuit>:-i:<filename>:-o:<filename>
                           Replace sequential memories with blackboxes + configuration file
```
