### ISSUE TITLE
DRET legal outside of debug mode

### ISSUE THREAD

**Issue by tzwaenn** [chipsalliance/rocket-chip#2022]
**Type of issue**: bug report 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
According to the debug specification, section 4.6 "Executing dret outside of Debug Mode causes an illegal instruction exception.". However, RocketChip seems to have the illegal exception tied to M mode - so M mode without debug mode does retire the DRET instruction istead of throwing an illegal exception.
Can be observed by having the first fetch after reset return the opcode 0x7b200073 of DRET.

**Please tell us about your environment:**
This issue was found with formal verifcation tool OneSpin 360 DV

**Comment by ernie-sifive** [comment]
Fixed, thanks for reporting this.
