### ISSUE TITLE
About the old file: PublicConfigs.scala

### ISSUE THREAD

**Issue by lactusec** [chipsalliance/rocket-chip#2047]
I'm a new learner of the Rocket Chip.
There is like a file 'rocket-chip/src/main/scala/PublicConfigs.scala' exist in many guide books of Rocket Chip, and it seems a old configuration file. 
So in which file can I find out the content of the old 'PublicConfigs.scala' now.

**Comment by colinschmidt** [comment]
Its been split up into `src/main/scala/system/Configs.scala`and `src/main/scala/subsystem/Configs.scala`

**Comment by lactusec** [comment]
> Its been split up into `src/main/scala/system/Configs.scala`and `src/main/scala/subsystem/Configs.scala`

Thank you very much
