### ISSUE TITLE
What is the meaning and function of fbus(front bus)?

### ISSUE THREAD

**Issue by clx782782** [chipsalliance/rocket-chip#2078]
I don’t know well what is the definition of “front bus” and what is the function of it.

And what is the difference between the “fbus” and the other buses?

Any suggestions will be appreciated.

**Comment by michael-etzkorn** [comment]
FrontBus is simply a TL crossbar for external TL requests. This reduces contention to the system bus with the rocket cores. 

A hierarchical design for the buses in the SoC is a useful categorization that allows for making decisions for each category on things like power and bandwidth maintenance. 

https://chipyard.readthedocs.io/en/latest/Generators/Rocket-Chip.html shows an example of how they're all connected in the default coherent topology.

Closing this issue. Further follow-up can be made by opening a question on StackOverflow.
