### ISSUE TITLE
there are two "MIN" element in the ArithMsg of TLAtomics object

### ISSUE THREAD

**Issue by gxlong1983** [chipsalliance/rocket-chip#2095]
Hi

I found that there are two "MIN" elements in the ArithMsg of TLAtomics object in the tilelink/Bundles.scala. It is different with the param definition of tilelink spec. Is it wrong?
Thanks.

**Comment by terpstra** [comment]
There is MIN and MINU. One is signed, the other is unsigned.

This corresponds with table 7.3 in the TileLink spec (v1.8)

**Comment by gxlong1983** [comment]
Yes, I know that there is MIN and MINU for tilelink atomic operation.
But, in the method of ArithMsg, I find two MIN instead of MIN and MINU.





At 2019-09-20 01:52:58, "Wesley W. Terpstra" <notifications@github.com> wrote:


There is MIN and MINU. One is signed, the other is unsigned.

This corresponds with table 7.3 in the TileLink spec (v1.8)

**Comment by terpstra** [comment]
Where? I see only one instance. Please cite filename and line numbers.

**Comment by terpstra** [comment]
Oh! you mean in the text output.
