### ISSUE TITLE
Is rocket-chip able to use store/load data for triggers?

### ISSUE THREAD

**Issue by hyf6661669** [chipsalliance/rocket-chip#2183]
![图片](https://user-images.githubusercontent.com/18757974/68270882-da425d00-0099-11ea-83c3-a314e58ee7eb.png)

In ```Breakpoint.scala```, it seems that rocket-chip can only use pc or load/store address for triggers.

**Comment by mwachs5** [comment]
That's correct. Data match triggers are not implemented.
