### ISSUE TITLE
Memory model access delays in emulator

### ISSUE THREAD

**Issue by miniskar** [chipsalliance/rocket-chip#2223]
Does the Rocket-chip emulator (using verilator) models main memory access delays ?

**Comment by aswaterman** [comment]
IIRC we are using a fixed-latency memory in the testbench, so cache refills
will be artificially fast in simulation.

**Comment by miniskar** [comment]
Is this a configurable parameter in some file?

**Comment by aswaterman** [comment]
It's static in the scala code.

https://github.com/chipsalliance/rocket-chip/blob/54237b5602a273378e3b35307bb47eb1e58cb9fb/src/main/scala/system/SimAXIMem.scala#L32

https://github.com/chipsalliance/rocket-chip/blob/42ae146a02617d8d8be9d965554f0c566b7445ae/src/main/scala/system/SimAXIMem.scala
