### ISSUE TITLE
Why do we have to flip the bits when accessing regFile?

### ISSUE THREAD

**Issue by JaewonHur** [chipsalliance/rocket-chip#2263]
In RocketCore.scala :: RegFile class
'access' function flips the address when reading rf.

like this. 
```scala
  private def access(addr: UInt) = rf(~addr(log2Up(n)-1, 0))
```

Why do we have to flip the addr bits?

Thank you.

**Comment by aswaterman** [comment]
x0 is hardwired to 0, so there are only 31 registers. Chisel doesn’t define
RAMs whose indices start at a nonzero value. This is a simple way of
emulating such a RAM.
