### ISSUE TITLE
dmInner debug_clock_gate can go meta-stable as dmactive_synced is async on falling edge

### ISSUE THREAD

**Issue by morse-michael** [chipsalliance/rocket-chip#2382]
**Type of issue**: bug report 

**Impact**: no functional change 

**Development Phase**:  proposal

**Other information**
The enable signal of debug_clock_gate gate (https://github.com/chipsalliance/rocket-chip/blame/master/src/main/scala/devices/debug/Debug.scala#L1686) can go meta-stable when dmactive_synced goes low because it is treated as an async reset (the dmactiveSync synchronising logic only synchronises the rising edge of this signal). 

Because of this, when dmactive is driven low by the JTAG clock domain it will occasionally result in setup/hold violations on clk_en_reg which is clocked by the cpu_clock and drives the enable signal of debug_clock_gate. This can result in the clock going meta-stable for 1 cycle, which doesn't matter for the async reset flops inside dmInner, but it does for the sync reset flops inside sb2tlOpt (which only receive a single reset clock). 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
You can reproduce this issue when running SDF annotated gatesim with asynchronous JTAG and CPU clocks by running the following openocd command in a loop:
openocd -c "mdw 0x10054d20" -c "exit"

**What is the current behavior?**
dmactive_synced is not synchronised on its falling edge when driving clock_en (https://github.com/chipsalliance/rocket-chip/blame/master/src/main/scala/devices/debug/Debug.scala#L1689)

**What is the expected behavior?**
dmactive_synced should get synchronised on both edges before it is used as clock enable

**Comment by ernie-sifive** [comment]
This is addressed in branch `multiple-reset-schemes-rebased` which will be merged in the next day or two.
