### ISSUE TITLE
Reading dpc register raise exception while spike doesn't

### ISSUE THREAD

**Issue by JaewonHur** [chipsalliance/rocket-chip#2390]
**Type of issue**: question

**Impact**: unknown

**Development Phase**: 

Running in machine mode,
Rocket chip raise exception when it reads debug pc, but spike doesn't.

Anyway, Could I find any documentation about specifics of Rocket chip other than RISC-V isa spec?

Thanks.

[test.zip](https://github.com/chipsalliance/rocket-chip/files/4419507/test.zip)

**Comment by aswaterman** [comment]
Accessibility of debug registers in M-mode is implementation-defined behavior.  However, we agree Spike should be changed to match the more rigid interpretation. Fixed in https://github.com/riscv/riscv-isa-sim/commit/5d5ee23f574583145cd2093a1fdab677e313e1d2
