### ISSUE TITLE
Random initialized reg_frm could cause fpu.illegal_rm and then illegel inst, is it true?

### ISSUE THREAD

**Issue by davidmlw** [chipsalliance/rocket-chip#2429]
https://github.com/chipsalliance/rocket-chip/blob/6f0a3f7aa374ad12d92876d367b498c661dd1d80/src/main/scala/tile/FPU.scala#L894
https://github.com/chipsalliance/rocket-chip/blob/4689a06cc704677a77cacd7d7cea09533f536c5c/src/main/scala/rocket/CSR.scala#L396

reg_frm is random initialized and could cause fpu.illegal_rm, and the CPU might enter a wrong state when powered on. Is this true?

**Comment by aswaterman** [comment]
Yes.  Software needs to initialize frm before using floating-point instructions.  The behavior is well defined.
