### ISSUE TITLE
FPU's fpmu.io.lt signal missed pipe?

### ISSUE THREAD

**Issue by zhouqinghua** [chipsalliance/rocket-chip#2445]
**Type of issue**: bug report | feature request | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown

**Development Phase**: request | proposal

**Other information**
 
FPToFP's input signal 'lt' is used directly to cmpare with 'in.bits.rm(0)'. 
in.bits is delayed by Pipe(io.in), but 'lt' missed pipe delay.  the pipeline will be dislocated in FPToFP module
**If the current behavior is a bug, please provide the steps to reproduce the problem:**
floating compare instructions will be affected when executed back2back in pipeline
i think "in.bits.rm(0) =/= io.lt" should be changed to "in.bits.rm(0) =/= pipe(io.lt)"
**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

**Comment by aswaterman** [comment]
No, because FPToInt also has a `Pipe` on its input, so `io.lt` is being used in the same pipeline stage it is produced.
