### ISSUE TITLE
Attaching L2 with rocket-chip

### ISSUE THREAD

**Issue by waleedbinehsan-lm** [chipsalliance/rocket-chip#2557]
Hey i am trying to attach L2 with rocket-chip but cant figure out how to do so. Im trying to attach InclusiveCache as L2.
Is there any document on this.

Thanks,
Waleed

**Comment by colinschmidt** [comment]
Chipyard integrates the InclusiveCache as an L2 with rocket-chip (and more) and has documentation.
See https://chipyard.readthedocs.io/en/latest/Customization/Memory-Hierarchy.html?highlight=L2#the-sifive-l2-cache
