### ISSUE TITLE
Functional cover points are not being generated in Rocket-chip RTL .

### ISSUE THREAD

**Issue by farhanaslam-lm** [chipsalliance/rocket-chip#2585]
Hi,
There is ccover invoked in ICache, DCache, TLB, and PTW of Rocket-Chip. The purpose of these is to generate cover-points for verification. But these points did not generate. Is there any method to generate these cover-points in v/sv files.

**Comment by sequencer** [comment]
Hi, functional cover points is not implemented in rocket-chip.
You can implement your own with extending https://github.com/chipsalliance/rocket-chip/blob/f506db09d4d37cbe74d21e74531f503a1b79a3a0/src/main/scala/util/Property.scala#L37
