### ISSUE TITLE
Can we make simulation by Cadence EDA tools? Such as irun?

### ISSUE THREAD

**Issue by jamesningd** [chipsalliance/rocket-chip#2592]
Can we make simulation by Cadence EDA tools? Such as irun?
I know the whole tools should be run by VCS, but we only have irun license for simulation.
So I want to try irun for simulate Rocket, is there anyone have this experience?
By the way, my Lunix is CentOS

**Comment by sequencer** [comment]
We currently only support verilator and vcs, PR is welcomed to support other simulator.
But as for those commercial simulators, a important problem is that, maintainer may have no access to that simulator, and cannot integrate with CI to maintain it.
