### ISSUE TITLE
Rocketchip behavior when reading pmpcfg2 register.

### ISSUE THREAD

**Issue by JaewonHur** [chipsalliance/rocket-chip#2637]
**Type of issue**: bug report 

**Impact**: unknown

**Development Phase**: request 

**Other information**
 

I am using Rocketchip default configuration from the commit `3f03ba`.

I think it is not the specification issue but 
there is a behavior inconsistency between Spike and Rocket.

When configuring both to use only 8 pmp registers.
Spike raise illegal instruction exception when trying to access `pmpcfg2` but Rocketchip doesn't.

I wonder is there any plan to make them consistent.
Here is the testcase.

[test.zip](https://github.com/chipsalliance/rocket-chip/files/5222587/test.zip)

**Comment by aswaterman** [comment]
In the test I wrote, pmpcfg2 was accessible in Spike.

**Comment by JaewonHur** [comment]
Ah, thanks.
