### ISSUE TITLE
Data Bypassing in Rocket Core

### ISSUE THREAD

**Issue by gkothar1** [chipsalliance/rocket-chip#2644]
Hello,

Are only the single-cycle Integer ALU results bypassed and all rest of the results (from mul, div, floating-point, memory) available after only register file writeback?

Regards,
Gaurav

**Comment by aswaterman** [comment]
Loads are bypassed.  Integer multiplication results are bypasses if using the pipelined multiplier (by setting mulUnroll == xLen).

**Comment by gkothar1** [comment]
Thank you @aswaterman
