### ISSUE TITLE
make RoccExampleConfig Error

### ISSUE THREAD

**Issue by tuihongshiyu** [chipsalliance/rocket-chip#2655]
The default config make has passed.
But there is error in make RoccExampleConfig:
demo@ubuntu:~/Documents/RocketChip/rocket-chip/emulator$ make CONFIG=RoccExampleConfig
mkdir -p /home/demo/Documents/RocketChip/rocket-chip/emulator/generated-src/
cd /home/demo/Documents/RocketChip/rocket-chip && java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /home/demo/Documents/RocketChip/rocket-chip/sbt-launch.jar "runMain freechips.rocketchip.system.Generator -td /home/demo/Documents/RocketChip/rocket-chip/emulator/generated-src -T freechips.rocketchip.system.TestHarness -C RoccExampleConfig "
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading settings for project rocket-chip-build-build-build from metals.sbt ...
[info] Loading project definition from /home/demo/Documents/RocketChip/rocket-chip/project/project/project
[info] Loading settings for project rocket-chip-build-build from metals.sbt ...
[info] Loading project definition from /home/demo/Documents/RocketChip/rocket-chip/project/project
[success] Generated .bloop/rocket-chip-build-build.json
[success] Total time: 0 s, completed Oct 7, 2020 4:13:32 PM
[info] Loading settings for project rocket-chip-build from metals.sbt,plugins.sbt ...
[info] Loading project definition from /home/demo/Documents/RocketChip/rocket-chip/project
[success] Generated .bloop/rocket-chip-build.json
[success] Total time: 1 s, completed Oct 7, 2020 4:13:33 PM
[info] Loading settings for project rocketchip from build.sbt ...
[info] Loading settings for project hardfloat from build.sbt ...
[info] Loading settings for project api-config-chipsalliance from build.sbt ...
[info] Loading settings for project chisel from build.sbt ...
Using addons: 
[info] Set current project to rocketchip (in build file:/home/demo/Documents/RocketChip/rocket-chip/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] running freechips.rocketchip.system.Generator -td /home/demo/Documents/RocketChip/rocket-chip/emulator/generated-src -T freechips.rocketchip.system.TestHarness -C RoccExampleConfig
[error] (run-main-0) java.lang.Exception: Unable to find part "RoccExampleConfig" from "ArrayBuffer(RoccExampleConfig)", did you misspell it or specify the wrong package path?
[error] java.lang.Exception: Unable to find part "RoccExampleConfig" from "ArrayBuffer(RoccExampleConfig)", did you misspell it or specify the wrong package path?ousCompile 0s
[error] 	at Chisel.package$throwException$.apply(compatibility.scala:436)
[error] 	at freechips.rocketchip.util.HasRocketChipStageUtils.$anonfun$getConfig$1(GeneratorUtils.scala:19)
[error] 	at scala.collection.IndexedSeqOptimized.foldRight(IndexedSeqOptimized.scala:65)
[error] 	at scala.collection.IndexedSeqOptimized.foldRight$(IndexedSeqOptimized.scala:72)
[error] 	at scala.collection.mutable.ArrayBuffer.foldRight(ArrayBuffer.scala:49)
[error] 	at freechips.rocketchip.util.HasRocketChipStageUtils.getConfig(GeneratorUtils.scala:14)
[error] 	at freechips.rocketchip.util.HasRocketChipStageUtils.getConfig$(GeneratorUtils.scala:13)
[error] 	at freechips.rocketchip.stage.phases.PreElaboration.getConfig(PreElaboration.scala:16)
[error] 	at freechips.rocketchip.stage.phases.PreElaboration.transform(PreElaboration.scala:26)
[error] 	at freechips.rocketchip.stage.phases.PreElaboration.transform(PreElaboration.scala:16)
[error] 	at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:267)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:89)
[error] Caused by: java.lang.ClassNotFoundException: RoccExampleConfig
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:92)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:264)
[error] 	at freechips.rocketchip.util.HasRocketChipStageUtils.$anonfun$getConfig$1(GeneratorUtils.scala:16)
[error] 	at scala.collection.IndexedSeqOptimized.foldRight(IndexedSeqOptimized.scala:65)
[error] 	at scala.collection.IndexedSeqOptimized.foldRight$(IndexedSeqOptimized.scala:72)
[error] 	at scala.collection.mutable.ArrayBuffer.foldRight(ArrayBuffer.scala:49)
[error] 	at freechips.rocketchip.util.HasRocketChipStageUtils.getConfig(GeneratorUtils.scala:14)
[error] 	at freechips.rocketchip.util.HasRocketChipStageUtils.getConfig$(GeneratorUtils.scala:13)
[error] 	at freechips.rocketchip.stage.phases.PreElaboration.getConfig(PreElaboration.scala:16)
[error] 	at freechips.rocketchip.stage.phases.PreElaboration.transform(PreElaboration.scala:26)
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 4 s, completed Oct 7, 2020 4:13:40 PM
make: *** [Makefrag-verilator:13: /home/demo/Documents/RocketChip/rocket-chip/emulator/generated-src/freechips.rocketchip.system.RoccExampleConfig.fir] Error 1

There were some issues like this but out of date

**Comment by sequencer** [comment]
Use `make CONFIG=freechips.rocketchip.system.RoccExampleConfig`.
