### ISSUE TITLE
how to stall/restart the pipeline of Rocket?

### ISSUE THREAD

**Issue by meton-robean** [chipsalliance/rocket-chip#2658]
what I want to do is that: 
when encountering a specific instruction address at Ins-Decode stage,  I want to stop the pipeline and handle something, after finishing it, I restart the pipeline so that the program continues to execute.

how can I achieve the operations above?  Which wires do I need to set when I stop/restart the pipeline?

**Comment by aswaterman** [comment]
Look at the `ctrl_stalld` signal... but please note that what you're trying to do isn't a supported feature, so you're on your own.

**Comment by meton-robean** [comment]
> Look at the `ctrl_stalld` signal... but please note that what you're trying to do isn't a supported feature, so you're on your own.

do I need to clear the ibuf when I restart the pipeline?
