### ISSUE TITLE
how to access to icache in my rocc accelerator?

### ISSUE THREAD

**Issue by meton-robean** [chipsalliance/rocket-chip#2669]
As I know, RoCC interface has mem io（HellaCacheIO)， which can access to dcache.  
Now I have a RoCC accelerator, but what I want to do is that I can access **icache** data on the accelerator side.  How can I extend icache interface in RoCC interface so that my accelerator can share the same icache with the Rocket?

**Comment by aswaterman** [comment]
There's no provision for this.  Other RoCC users have used a dedicated I$ for their coprocessor.
