### ISSUE TITLE
Reg missa not encoded with M extension

### ISSUE THREAD

**Issue by Uzair540** [chipsalliance/rocket-chip#2682]
When I try to config the file to make RV32IM Soc.I did not get the correct misa base field value of bits by comparing it With the privileged architecture RISCV. According  to RISCV specs, misa MSB bits should be 01 for the 32bit core and when I add M extension I get MSB 10 which indicates its 64-bit core, not the 32

**Comment by aswaterman** [comment]
I'm merging this issue with https://github.com/chipsalliance/rocket-chip/issues/2681 -- please demonstrate that the value is incorrect when executing software on the core, i.e., that `csrr t0, misa` produces the wrong value into the `t0` register.  The value observed in RTL is irrelevant.
