### ISSUE TITLE
How can I reduce Rocket Chip DRAM size from 256MB ?

### ISSUE THREAD

**Issue by Uzair540** [chipsalliance/rocket-chip#2690]
I am having integer overflow error because of the large 256MB size of DRAM. 
![issue ram](https://user-images.githubusercontent.com/54856325/97521342-32672300-19bf-11eb-9d84-7421edd031db.jpg)
I want to map rocketchip generated SOC on my FPGA Arty A7-35.When I map this I got overflow integer error due to the large size of RAM
![issue 3](https://user-images.githubusercontent.com/54856325/97532008-461e8380-19d7-11eb-9db1-346b31ad01f8.png)

I am using 64kb data and instruction cache I want to reduce RAM size of rocket chip. From where in scala /Chisel file I can make changes? 
Line 224 gives me an error of integer flow which means my DRAM size is very large 256MB.How can I change my RAM size from my scala code Can you elaborate me the path  ?
@aswaterman @yunsup

**Comment by aswaterman** [comment]
https://github.com/chipsalliance/rocket-chip/blob/630600d860a0ff0ec1e290931d301cc6f2b96fe0/src/main/scala/subsystem/Configs.scala#L392

**Comment by Uzair540** [comment]
@aswaterman can you please elaborate what kind of information this variable is giving about the size of RAM,How many address bits are there and width of the memory?

**Comment by aswaterman** [comment]
That's the number of bytes in the main memory.  Reducing that number will reduce the number of rows in the RAM.

**Comment by Uzair540** [comment]
thanks I got your point
