### ISSUE TITLE
Rocket Chip mapping on FPGA

### ISSUE THREAD

**Issue by Uzair540** [chipsalliance/rocket-chip#2698]
I am having issue in mapping rocket chip to FPGA ?Can you suggest me the boards or FPGA at which I can map my rocket chip ?
https://github.com/ucb-bar/fpga-zynq
Is fpga-zynq help me in this issue?
My ultimate goal is to map SOC generated from rocket chip on to the fpga
@aswaterman  @yunsup @hcook

**Comment by sequencer** [comment]
I suggest you can take a look at diplomacy firstly.
After you understanding the SoC generation related codes, you can take a look at https://github.com/sifive/fpga-shells to see how to map a RocketChip generated SoC into an FPGA.
My suggestion is to read documentation and code firstly, then turn to issue for help.
https://github.com/ucb-bar/chipyard also have a lot of documentations where you can find a lot of documentations.
