### ISSUE TITLE
What is the meaning of HellaCacheFactory?

### ISSUE THREAD

**Issue by jamesningd** [chipsalliance/rocket-chip#2709]
Hi all,
I want to change a little for the DCache IO port, however, I can't understand the IO define of DCache.
The sentence "new DCache(tile.hartId, tile.crossing)(p)" is how to new it, but I can't see any IO port there.
Anyone can tell me the meaning of this and how to add new IO in DCache? 
```scala
object HellaCacheFactory {
  def apply(tile: BaseTile)(p: Parameters): HellaCache = {
    if (tile.tileParams.dcache.get.nMSHRs == 0)
      new DCache(tile.hartId, tile.crossing)(p)
    else
      new NonBlockingDCache(tile.hartId)(p)
  }
}
```

**Comment by sequencer** [comment]
`HellaCacheFactory` consumes `Tile`, based the DCache `nMSHRs` parameter to decide initiating a blocking or none blocking cache.

As for adding IOs, you should add them to `HellaCacheBundle`, which is IO between `DCache` or `NonBlockingDCache` to core, but modification to rocket-chip is not supported by issue, you can try to add them, and use it on your own risk,

**Comment by jerryhethatday** [comment]
> `HellaCacheFactory` consumes `Tile`, based the DCache `nMSHRs` parameter to decide initiating a blocking or none blocking cache.
> 
> As for adding IOs, you should add them to `HellaCacheBundle`, which is IO between `DCache` or `NonBlockingDCache` to core, but modification to rocket-chip is not supported by issue, you can try to add them, and use it on your own risk,

Could you please clarify what MSHR is?

**Comment by ly0** [comment]
@jerryhethatday  It's **M**icro**S**oft's **H**uman**R**esource!

**Comment by sequencer** [comment]
Miss Status Handling Register
@ly0 please…

**Comment by jerryhethatday** [comment]
@sequencer  Thanks. When nMSHRs  === 0,  the cache is non blocking.  Does nMSHR indicate  number of misses to be outstanding in the cache before blocking?

**Comment by jamesningd** [comment]
> 

Hi Jerry,
It is a nonblocking Cache, thank you

**Comment by jamesningd** [comment]
> > `HellaCacheFactory` consumes `Tile`, based the DCache `nMSHRs` parameter to decide initiating a blocking or none blocking cache.
> > As for adding IOs, you should add them to `HellaCacheBundle`, which is IO between `DCache` or `NonBlockingDCache` to core, but modification to rocket-chip is not supported by issue, you can try to add them, and use it on your own risk,
> 
> Could you please clarify what MSHR is?



> > 
> 
> Hi Jerry, It is a nonblocking Cache, thank you

Hi Jerry
Sorry， It is blocking Cache, please neglect the first reply.
