### ISSUE TITLE
How to configure GPIO?

### ISSUE THREAD

**Issue by Talha-Ahmed-1** [chipsalliance/rocket-chip#2712]
I have configured an SoC by using Rocket-Chip SoC generator but I am unable to find any parameter that can configure GPIO(General Purpose Input Output) for the SoC.
Is it automatically configured?
How can I explicitly configure it?

**Comment by sequencer** [comment]
You can take a look at [sifive/freedom](https://github.com/sifive/freedom), it depends on [sifive/sifive-blocks](https://github.com/sifive/sifive-blocks), but it’s mostly undocumented.
