### ISSUE TITLE
Why rocket chip is called SOC Generator?

### ISSUE THREAD

**Issue by Uzair540** [chipsalliance/rocket-chip#2713]
If rocket chip not directly give us SOC why we called it SOC generator?As I understand from my expertise rocket chip genertor generates SOC with I/O and we have to connect different I/O to devices which we wish to add in our SOC.I am little confused in this matter can you guide me if I have some misconception on this ?
@aswaterman @hcook

**Comment by sequencer** [comment]
RocketChip is a SoC generator framework, to be exact, “diplomacy” is.
In RocketChip it can provide entire subsystem with multi cores, bus interconnection, PLIC, CLIC, debug, etc. These devices are part of SoC, which is called subsystem.
What you mean is a full chip. But full chip needs some additional devices which is not included in the rocket-chip repository, you can take a look at [sifive/sifive-blocks](https://github.com/sifive/sifive-blocks). There are other IPs not vended opensource, which you need blackbox and use diplomacy to do the integration, as for these IPs, you can take a look at [sifive/fpga-shells](https://github.com/sifive/fpga-shells) to integrate blackbox to diplomacy.
You can take a look at this [paper](https://carrv.github.io/2017/papers/cook-diplomacy-carrv2017.pdf) for more informations.
