### ISSUE TITLE
some risc-v program can not run

### ISSUE THREAD

**Issue by whutmsy** [chipsalliance/rocket-chip#2731]
@sequencer , I have successfully put rocket on fpga and running. But some program can run, others not. Why it happend？
![b](https://user-images.githubusercontent.com/39824017/99137935-f6db8280-2667-11eb-9035-f4b6b1b81969.PNG)

**Comment by sequencer** [comment]
There are no enough informations for me to help you debug this. If some program cannot be executed by 
https://github.com/chipsalliance/rocket-chip#2-compiling-and-executing-a-custom-program-using-the-emulator
You can open this issue again.
