### ISSUE TITLE
How to write a wrapper to connect GPIO

### ISSUE THREAD

**Issue by shahzaibk23** [chipsalliance/rocket-chip#2734]
I'm trying to generate an SoC, but when I simulate it, it shows too many ports.
How do i write a wrapper that will connect GPIO into the ports of the generated SoC.

**Comment by sequencer** [comment]
Hi, @shahzaibk23, you can take a look at:
https://github.com/sifive/sifive-blocks/tree/master/src/main/scala/devices/gpio
Usage can be found at 
https://github.com/ucb-bar/chipyard/tree/master/generators/chipyard/src/main/scala/DigitalTop.scala#L21
If you have any other questions about this, please open this issue again.
