### ISSUE TITLE
two each, a typo

### ISSUE THREAD

**Issue by jerryhethatday** [chipsalliance/rocket-chip#2735]
https://github.com/chipsalliance/rocket-chip/blob/c28c051f85e0118195749549939be58ef9bfd19a/src/main/scala/diplomacy/package.scala#L62

**Comment by mwachs5** [comment]
thanks! feel free to open a PR to fix this!

**Comment by jerryhethatday** [comment]
> thanks! feel free to open a PR to fix this!

Sorry about the late reply, I am busy reading thru the rocketchip codebase, I found some other typos, maybe I can open  a PR to fix all these after finishing the diplomacy source code part. 
Also, I wanna know if there is something like question template with which I can post my question on the codebase, so that I can get a quicker response, I post lots of problems recently, and did not get any reply, I wonder if I did something wrong???
Thanks for your harwork!
