### ISSUE TITLE
ubuntu build error~~

### ISSUE THREAD

**Issue by weisuolong** [chipsalliance/rocket-chip#2777]
/home/weisu/rocket-tools/riscv-gnu-toolchain/lib/gcc/riscv64-unknown-elf/7.2.0/../../../../riscv64-unknown-elf/bin/ld:/home/weisurocket-tools/riscv-tests/build/../isa/../env/v/link.ld:0: syntax error
collect2: error: ld returned 1 exit status
make[1]: *** [/home/weisu/rocket-tools/riscv-tests/build/../isa/Makefile:75: rv32uc-v-rvc] Error 1
make: *** [Makefile:29: isa] Error 2

i got one error  when i build.sh    

help~~

**Comment by michael-etzkorn** [comment]
Environment set-up can be a painful debugging process. Closed to age.
