### ISSUE TITLE
Is the Wire wrapper necessary?

### ISSUE THREAD

**Issue by jerryhethatday** [chipsalliance/rocket-chip#2835]
https://github.com/chipsalliance/rocket-chip/blob/46c88b71056581a6bf2a0c4febd5ec3d768c6c59/src/main/scala/tilelink/Bundles.scala#L245
`TLBundle` class inside the _`src/main/scala/tilelink/Bundles.scala`_ has following declarations:

```
// Emulate a Bundle with elements abcde or ad depending on params.hasBCE

  private val optA = Some                (Decoupled(new TLBundleA(params)))
  private val optB = params.hasBCE.option(Decoupled(new TLBundleB(params)).flip)
  private val optC = params.hasBCE.option(Decoupled(new TLBundleC(params)))
  private val optD = Some                (Decoupled(new TLBundleD(params)).flip)
  private val optE = params.hasBCE.option(Decoupled(new TLBundleE(params)))

  def a: DecoupledIO[TLBundleA] = optA.getOrElse(**Wire**(Decoupled(new TLBundleA(params))))
  def b: DecoupledIO[TLBundleB] = optB.getOrElse(**Wire**(Decoupled(new TLBundleB(params))))
  def c: DecoupledIO[TLBundleC] = optC.getOrElse(**Wire**(Decoupled(new TLBundleC(params))))
  def d: DecoupledIO[TLBundleD] = optD.getOrElse(**Wire**(Decoupled(new TLBundleD(params))))
  def e: DecoupledIO[TLBundleE] = optE.getOrElse(**Wire**(Decoupled(new TLBundleE(params))))
```

Taking the `def b: DecoupledIO[TLBundleB] = optB.getOrElse(**Wire**(Decoupled(new TLBundleB(params))))` as an example, I felt confused about why there is a `Wire` wrapper. When the optB is None(params.hasBCE be false), this will return the value of  `Wire(Decoupled(new TLBundleA(params)))`. Consequently it is a boundType instead of unbound. But the a and d will always be unbound type. I think it is not necessary and can be deleted. 
Are my understandings for this right? 
Thanks!
@hcook  @terpstra  @colinschmidt @ducky64  @jackkoenig

**Comment by terpstra** [comment]
The wire is there so that if you drive the value, it works, but discards the value.
This was done for backwards compatibility with how the bundle used to be (all sub-bundles existed unconditionally).
