### ISSUE TITLE
Does rocket chip core has register to store current privilege?

### ISSUE THREAD

**Issue by zhushaofeng1992** [chipsalliance/rocket-chip#2855]
Does rocket chip core has register to store current privilege? How can the core decide that the access to a M-mode CSR is from M-mode code or S-mode code( in this case, the core will not be able to access the CSR)

**Comment by mwachs5** [comment]
Search for `prv` in the codebase: https://github.com/chipsalliance/rocket-chip/blob/86a2f2cca699f149bcc082ef2828654a0a4e3f4b/src/main/scala/rocket/CSR.scala#L25
