### ISSUE TITLE
ICacheModule refill and invalidate field coupling issue

### ISSUE THREAD

**Issue by jerryhethatday** [chipsalliance/rocket-chip#2875]
In the ICacheModule, there is following code snippet:
```    val vb_array = Reg(init=Bits(0, nSets*nWays))
  when (refill_one_beat) {
    s := refillError
    // clear bit when refill starts so hit-under-miss doesn't fetch bad data
    vb_array := vb_array.bitSet(Cat(repl_way, refill_idx), refill_done && !invalidated)
  }
  val invalidate = Wire(init = io.invalidate)
  when (invalidate) {
    vb_array := Bits(0)
    invalidated := Bool(true)
  }
```
Are there chances that `refill_done && !invalidated` and `invalidate` are both asserted? During the last beat refill while invalidated remains false, are there edge cases that  cpu could assert the  io.invalidate ? And is the logic here still right if this rare circumstance happens? When both the `refill_done && !invalidated` and `invalidate` are true, the `vb_array` will be set to 0 anyway according to the last connection wins scheme right?
I am new to logical design, and hope I dont post a silli question. Thanks!
@hcook @aswaterman

**Comment by aswaterman** [comment]
You are right to be worried about this kind of situation, but I claim the microarchitecture does the right thing in the scenario you've described.
