### ISSUE TITLE
[chisel-3.5] new chisel3.cover clashes with freechips.rocketchip.util.property.cover

### ISSUE THREAD

**Issue by ekiwi** [chipsalliance/rocket-chip#2884]
Just a heads up that the next release of Chisel is going to have its own `chisel3.cover(Bool, String)` and that is going to clash with `freechips.rocketchip.util.property.cover` in quite some places.
There are two solutions here:
1) change the uses of `cover` to explicitly use `property.cover`
2) I would be happy to work with you all to try and make the `chisel3.cover` a good drop in replacement for your old custom solution

Kevin

**Comment by ekiwi** [comment]
@debs-sifive

**Comment by debs-sifive** [comment]
Thanks for the heads up! We should be ok with explicitly stating which cover to use for now.

**Comment by michael-etzkorn** [comment]
Handled here: https://github.com/chipsalliance/rocket-chip/commit/92077511baedf2c8a07f7774d5c272682a975b4b
