### ISSUE TITLE
Possible Error in the ECC-correctable Logic in ICache

### ISSUE THREAD

**Issue by soulzatzero** [chipsalliance/rocket-chip#2888]
The code listed below derives whether there's a correctable data mistake by the OR of the canDetect members of the ECC codes chosen by tag and data field. Yet in DCache this is decided by the OR of canCorrect members of the respective ECC codes chosen, and here using canDetect doesnt seem to make sense. Would you please explain why you use canDetect to get correctable logic if I'm wrong? Thanks!
https://github.com/chipsalliance/rocket-chip/blob/4276f17f989b99e18e0376494587fe00cd09079f/src/main/scala/rocket/ICache.scala#L51

**Comment by solomatnikov** [comment]
ICache is read-only

**Comment by soulzatzero** [comment]
Thanks!

**Comment by soulzatzero** [comment]
Thanks!
