### ISSUE TITLE
scanInsns confusion in FrontEnd module

### ISSUE THREAD

**Issue by jerryhethatday** [chipsalliance/rocket-chip#2912]
The iterative method scanInsns in the frontend is hard to understand when it applies to chisel hardware. I have the following question:

1. When `fetchWidth = 1` and instruction width is 4B, it seems  that `s2_valid && s2_btb_resp_valid && s2_btb_resp_bits.bridx === idx && valid && !rvc` will always be asserted when `s2_valid && s2_btb_resp_valid` is true , in this case the btb will be flushed, is this the expected behavior? If not, where in the codebase prevent this unexpected flushing happen?
```
      when (s2_valid && s2_btb_resp_valid && s2_btb_resp_bits.bridx === idx && valid && !rvc) {
        // The BTB has predicted that the middle of an RVI instruction is
        // a branch! Flush the BTB and the pipeline.
        btb.io.flush := true
        fq.io.enq.bits.replay := true//hjr todo why we have to replay this?
        wrong_path := true
        ccover(wrong_path, "BTB_NON_CFI_ON_WRONG_PATH", "BTB predicted a non-branch was taken while on the wrong path")
      }
```
2. I have trouble figuring the rationale of updating BTB in frontend. According to my understanding, Seems that when there is a btb miss(`s2_btb_resp_valid` to be false) and the instruction fetched itself is a bht predicted taken branch, or a jump, the btb should be updated at frontend. I felt like this is unnecessary, because we even dont know what the tartget address is.
I know the codebase is correct. I am just confused, can anyone give me some clue about the above 2 confusions. 
Thanks!
@aswaterman @mwachs5

**Comment by aswaterman** [comment]
Updating the BTB in the frontend prevents short loops from being mispredicted multiple times (since multiple loop iterations might be fetched before the first copy of the branch even executes).

The target address _is_ known in the frontend (except for indirect jumps).
