### ISSUE TITLE
when  'git submodule update --init --recursive', Cloning into '/xxx/xxx/rocket-tools/fsf-binutils-gdb'... is   failed

### ISSUE THREAD

**Issue by lpppeipei** [chipsalliance/rocket-chip#2917]
**Type of issue**: bug report | feature request | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown

**Development Phase**: request | proposal

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

**Comment by michael-etzkorn** [comment]
I imagine this can be fixed by following the `README`'s instruction for tool-setup

https://github.com/chipsalliance/rocket-chip#setting-up-the-riscv-environment-variable

**Comment by michael-etzkorn** [comment]
Closed due to lack of activity and being user specific.
