### ISSUE TITLE
VSIM MAKE ERRO

### ISSUE THREAD

**Issue by Mingxintang-coder** [chipsalliance/rocket-chip#2922]
**environment:**

    - OS: `ubuntu 16.04`
    - gcc  4.8.5
    - g++ 4.8.5

**error**

collect2: error: ld returned 1 exit status
Makefile:104: recipe for target 'product_timestamp' failed
make[1]: *** [product_timestamp] Error 1
make[1]: Leaving directory '/home/tmx/rocket-chip/vsim/csrc'
Make exited with status 2
Makefrag:69: recipe for target 'simv-freechips.rocketchip.system-DefaultConfig' failed
make: *** [simv-freechips.rocketchip.system-DefaultConfig] Error 2

**Makefrag in vsim fold**
VCS = vcs -full64

VCS_OPTS = -notice -line +lint=all,noVCDE,noONGS,noUI -error=PCWM-L -timescale=1ns/10ps -quiet \
	+rad +v2k +vcs+lic+wait \
	+vc+list -CC "-I$(VCS_HOME)/include" \
	-CC "-I$(RISCV)/include" \
	-CC "-std=c++11" \
	-CC "-Wl,-rpath,$(RISCV)/lib" \
	$(RISCV)/lib/libfesvr.a \
	-sverilog \
	+incdir+$(generated_dir) \
	+define+CLOCK_PERIOD=1.0 $(sim_vsrcs) $(sim_csrcs) \
	+define+PRINTF_COND=$(TB).printf_cond \
	+define+STOP_COND=!$(TB).reset \
	+define+RANDOMIZE_MEM_INIT \
	+define+RANDOMIZE_REG_INIT \
	+define+RANDOMIZE_GARBAGE_ASSIGN \
	+define+RANDOMIZE_INVALID_ASSIGN \
	+define+RANDOMIZE_DELAY=0.1 \
	+define+MODEL=$(MODEL) \
	+libext+.v \

what can i do ?
thanks!

**Comment by michael-etzkorn** [comment]
This is over a year old and there's not enough info to debug this that it won't be transferred to a discussion at this time.
