### ISSUE TITLE
How to add an interface for RoCC that can read a vector of data from L1DCache?

### ISSUE THREAD

**Issue by Houlx** [chipsalliance/rocket-chip#2929]
I'm working on an RoCC that processes data in parallel. However I found that the interface for RoCC to read data from L1DCache only read one data at a time. I know it is hard to modify the current existing interface, but is it possible to add another high width interface that read more data at a time only for RoCC, which  has no effect on other parts?

**Comment by SihaoLiu** [comment]
RoCC provides tlNode and atlNode, which allows you to access the system bus directly. You can check the [gemmini code](https://github.com/ucb-bar/gemmini/blob/master/src/main/scala/gemmini/DMA.scala#L187-L249) and see how they did it (basically adding DMA to RoCC). Reading vector data from L1DCache directly seems a big hack to the current hellacache.
