### ISSUE TITLE
Question about D$ meta design

### ISSUE THREAD

**Issue by w1nda** [chipsalliance/rocket-chip#2957]
https://github.com/chipsalliance/rocket-chip/blob/185cac830746df9a22465e3267e6d47e01567bc3/src/main/scala/rocket/HellaCache.scala#L328-L331

in current D$ design, the meta possibly be writen and read at the same cycle, but the [mem](https://www.chisel-lang.org/api/latest/chisel3/SyncReadMem.html) meta used doesn't support that, so if there is something unpredictable？

**Comment by jerryz123** [comment]
I believe the microarchitecture checks for the hazard and avoids a read to the same address as the write.
The logic for this is distributed throughout various places in the NBDCache (the only place where this module is used.)
