### ISSUE TITLE
a error i meet when i run vlsi flow

### ISSUE THREAD

**Issue by 1bing2** [chipsalliance/rocket-chip#2970]
when i run vlsi flow on chipyard,i get  a error.
i run the command ：make buildfile CONFIG=TinyRocketConfig

error:Total time: 59 s, completed Apr 28, 2022 9:41:02 PM
/home/lee/Desktop/riscv-boom/verilator/chipyard/common.mk:110: recipe for target 'generator_temp' failed
make: *** [generator_temp] Error 1

**Type of issue**: bug report | feature request | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown

**Development Phase**: request | proposal

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

**Comment by sequencer** [comment]
This should be a bug report to chipyard from your description
