### ISSUE TITLE
[Bug Report] The width of xtval is less than XLEN

### ISSUE THREAD

**Issue by Phantom1003** [chipsalliance/rocket-chip#2975]
**Type of issue**: bug report
**Impact**: unknown
**Development Phase**: proposal
**Other information**
In the following test case, we jump to 0x2000000080000000, which is an illegal address out of the virtual address range. 
Rocket first compresses this illegal address to 0xffffff8080000000, and saves it in mtval (because of access fault).
```
[rocket] 3 0x00800001a4 (0x00a5e5b3) x11 0x2000000080000000
[spike]  core   0: 0x00000000800001a4 (0x00a5e5b3) or      a1, a1, a0
[rocket] 3 0x00800001a8 (0x00058067)
[spike]  core   0: 0x00000000800001a8 (0x00058067) jr      a1
[rocket] 3 0x0080000004 (0x34302f73) x30 0xffffff8080000000
[spike]  core   0: exception trap_instruction_access_fault, epc 0x2000000080000000
[spike]  core   0:           tval 0x2000000080000000
[spike]  core   0: 0x0000000080000004 (0x34302f73) csrr    t5, mtval
[error] WDATA EMU 2000000080000000 , DUT ffffff8080000000
[error] check board clear 30 error
```
[rocket-5.zip](https://github.com/chipsalliance/rocket-chip/files/8618455/rocket-5.zip)

According to the privilege specification, the width of xtval should be XLEN bits. We think the compressed address may confuse the trap handler to handle the exception. Although the top address bits can be omitted in hardware, the address is still 64 bits for the software and they need the raw address information to perform their functions.

**Please tell us about your environment:**
    - version: edc8d40

**Comment by aswaterman** [comment]
This is not a bug; the ISA explicitly permits it: https://github.com/riscv/riscv-isa-manual/blob/55cd85c891f21302cdd9d1bfa60ee87a7a241f93/src/supervisor.tex#L802-L803
