### ISSUE TITLE
[Bug Report] incorrect xs field check under VS

### ISSUE THREAD

**Issue by Phantom1003** [chipsalliance/rocket-chip#2980]
**Type of issue**: bug report
**Impact**: unknown
**Development Phase**: proposal
**Other information**
In the following test case, we first enable mpv and xs bit in mstatus, and then set up xs field in vsstatus. With the xs field, any custom instructions should not raise illegal signal.
From the co-simulation result, spike successfully executes the rocc instruction, while rocket throws an exception.
```
[rocket] 3 0x00080000178 (0x30005073)
[spike]  core   0: 0x0000000080000178 (0x30005073) csrwi   mstatus, 0
[rocket] 3 0x0008000017c (0x000182b7) x 5 0x0000000000018000
[spike]  core   0: 0x000000008000017c (0x000182b7) lui     t0, 0x18
[rocket] 3 0x00080000180 (0x3002a073)
[spike]  core   0: 0x0000000080000180 (0x3002a073) csrs    mstatus, t0
[rocket] 3 0x00080000184 (0x0010031b) x 6 0x0000000000000001
[spike]  core   0: 0x0000000080000184 (0x0010031b) addiw   t1, zero, 1
[rocket] 3 0x00080000188 (0x02731313) x 6 0x0000008000000000
[spike]  core   0: 0x0000000080000188 (0x02731313) slli    t1, t1, 39
[rocket] 3 0x0008000018c (0x30032073)
[spike]  core   0: 0x000000008000018c (0x30032073) csrs    mstatus, t1
...
[rocket] 3 0x000800001a4 (0x20029073)
[spike]  core   0: 0x00000000800001a4 (0x20029073) csrw    vsstatus, t0
[rocket] 3 0x000800001a8 (0x20002573) x10 0x8000000200018000
[spike]  core   0: 0x00000000800001a8 (0x20002573) csrr    a0, vsstatus
...
[rocket] 3 0x000800001bc (0x30200073)
[spike]  core   0: 0x00000000800001bc (0x30200073) mret
[rocket] 1 0x000800001c0 (0x00000613) x12 0x0000000000000000
[spike]  core   0: 0x00000000800001c0 (0x00000613) li      a2, 0
[rocket] 3 0x00080000004 (0x34302f73) x30 0x000000000000700b
[spike]  core   0: 0x00000000800001c4 (0x0000700b) custom0.rd.rs1.rs2 (args unknown)
[error] PC SIM 00000000800001c4, DUT 0000000080000004
[error] INSN SIM 0000700b, DUT 34302f73
```

[rocket-7.zip](https://github.com/chipsalliance/rocket-chip/files/8646809/rocket-7.zip)

We believe there is a typo in the rocc_illegal signal, where the `.vs` should be `.xs`:
https://github.com/chipsalliance/rocket-chip/blob/850e1d5d56989f031fe3e7939a15afa1ec165d64/src/main/scala/rocket/CSR.scala#L854

**Please tell us about your environment:**
    - version: edc8d40

**Comment by Phantom1003** [comment]
@aswaterman Would you please confirm this report?

**Comment by aswaterman** [comment]
I would have said this differently: RoCC and Hypervisor extension are currently incompatible.  This is a request for a new feature, not a report about a bug.

Please work with the folks at UC Berkeley who use RoCC to make sure they are OK with whatever you propose.  I don't work with RoCC.  (cc @jerryz123 to see who should work with you on this PR.)

**Comment by Phantom1003** [comment]
I still insist that this is a bug, and this report contains two problems.

1. The xs bits of vsstatus is writable, which is inconsistent with the specification:
> Read-only fields SD and XS summarize the extension context status as it is visible to VS-mode
only. For example, the value of the HS-level sstatus.FS does not affect vsstatus.SD.

https://github.com/chipsalliance/rocket-chip/blob/850e1d5d56989f031fe3e7939a15afa1ec165d64/src/main/scala/rocket/CSR.scala#L1337-L1347

2. The rocc_illegal signal incorrectly uses vs field, which is used for vector_illegal. And if RoCC and Hypervisor extension are currently incompatible, there should be `reg_mstatus.v && usingRoCC` instead of `reg_vsstatus.vs`.
https://github.com/chipsalliance/rocket-chip/blob/850e1d5d56989f031fe3e7939a15afa1ec165d64/src/main/scala/rocket/CSR.scala#L851-L854

**Comment by aswaterman** [comment]
I agree XS should not be directly writable, but it’s only a bug that manifests with RoCC enabled, and so the maintainers/users of RoCC (i.e. not me :-)) should deal with it.

I also agree that rocc_illegal should use XS, not VS, but this is really an unrelated topic. Please keep bug reports to one bug at a time.

**Comment by jerryz123** [comment]
The last time this came up was 2 years ago. This issue gives me deja-vu.

I believe XS should be read-only, but hard wired to dirty when RoCC is present. https://github.com/chipsalliance/rocket-chip/pull/2508

**Comment by aswaterman** [comment]
I agree that’s the lowest-effort-but-seemingly-correct thing to do. It also makes it obvious what to do with vsstatus.

**Comment by Phantom1003** [comment]
Thanks to Andrew and Jerry, the bugs mentioned have been fixed.
