### ISSUE TITLE
How to rightly rotate the graphml layout 

### ISSUE THREAD

**Issue by jerryhethatday** [chipsalliance/rocket-chip#2981]
It seems not a good place to post this problem here . But I know the rocketchip community deals with this problem either. 
I opened the generated diplomacy connection graph in yEd version 3.22, and It's a mess
![image](https://user-images.githubusercontent.com/1823246/167528126-4d8f13f6-059d-4020-8572-441d38f24f3d.png)

I then use the one-click layout feature to auto layout this, it worked just fine:
![image](https://user-images.githubusercontent.com/1823246/167528263-66b069e7-9496-4705-846e-3ef03b60a4fe.png)
However, the layout direction is just wrong, I need to rotate it 90degree clokcwisely, I searched online, and found the following option:
![image](https://user-images.githubusercontent.com/1823246/167528441-d9efdcbc-9777-4420-a1a3-fac1bc7e383b.png)
However, after this operation, seems that lots of the elements are not well aligned and it's a mess.
![image](https://user-images.githubusercontent.com/1823246/167528514-ecd83cca-2258-4c4b-a1df-1fe897e33dd5.png)
So, my problem is simple, hot can I check this graph rightly, sorry for the overkill of posting an issue here.

**Comment by jerryhethatday** [comment]
@hcook

**Comment by sequencer** [comment]
The generated `graphml` doesn't contain any layout informations. that should be an issue to your `graphml` viewer(I bet you are using `yEd`), for simplest way, you can directly export it to `pdf` and rotate which via your pdf viewer.
