### ISSUE TITLE
Remove RocketTilesKey

### ISSUE THREAD

**Issue by jerryz123** [chipsalliance/rocket-chip#3031]
**Type of issue**: other enhancement

**Impact**: API modification 

**Development Phase**: proposal

**Other information**
 

`RocketTilesKey` should be removed in favor of `TilesLocated`

**Comment by michael-etzkorn** [comment]
closed by #3133 

(Fun GitHub tip: if you do `closes: #3031` in your PR, it'll auto close the related issue once merged)
