### ISSUE TITLE
Difference between WithNBigCore v/s With1TinyCore

### ISSUE THREAD

**Issue by nishanthsmurthy24** [chipsalliance/rocket-chip#3069]
Hi,

Can anyone explain the Architectural difference between A Rocket Config - `WithNBigCores(1)` and `With1TinyCore`?

I tried looking up the Documentation but there is nothing about this.

Thanks in advance.

**Comment by michael-etzkorn** [comment]
Since we already have a documentation meta issue #2960, I'll backlink this issue to that and close it. Feel free to open a discussion on the discussion page where we can go into more detail about the configuration parameters.
