### ISSUE TITLE
what function does homogeneous have ?

### ISSUE THREAD

**Issue by napian-yun** [chipsalliance/rocket-chip#3075]
"val homogeneous = TLBPageLookup(edge.manager.managers, xLen, p(CacheBlockBytes), BigInt(1) << pgIdxBits)(mpu_physaddr).homogeneous"---from TLB.scala

Could you tell me what mean  homogeneous  is ?

**Comment by michael-etzkorn** [comment]
Homogeneous has to do with page size alignment. We can discuss more on StackOverflow or the discussion page!
