### ISSUE TITLE
[Proposal] Adding ZenithalHourlyRate to rocket-chip maintainer

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [chipsalliance/rocket-chip#3244]
**Type of issue**: other enhancement

**Impact**: unknown

**Development Phase**: proposal

I'm the main author of Zk/Zb support for rocket-chip (#2950), and I've opened some other [enhancement PRs](https://github.com/chipsalliance/rocket-chip/pulls?q=is%3Apr+author%3AZenithalHourlyRate+) including adding riscv-arch-test CI.

I'm affiliated with [PLCT](https://github.com/plctlab) as an intern and @sequencer is my mentor. I have helped and will continue to help him maintain rocket-chip.

I have been in the open source community for some time, and my open source contribution can be found on my github profile and my [homepage](https://zenithal.me).

I think I have met the requirement for a maintainer so I hereby request to promote myself to one maintainer of rocket-chip.

I also want to be added to the chipsalliance github organization.

I wonder what else should be done to reach these goals.

**Comment by sequencer** [comment]
Approved in dev meeting. Invited you to [rocket-chip-maintainers](https://github.com/orgs/chipsalliance/teams/rocket-chip-maintainers)
