### ISSUE TITLE
How to config cluster of BOOM cores and cluster of Rocket cores to compose a Heterogeneous SoC?

### ISSUE THREAD

**Issue by Leon924** [chipsalliance/rocket-chip#3286]
@michael-etzkorn @aswaterman 
Hi, guys:
      Does chipyard and rocket-chip generator now support a heterogeneous cluster of BOOM cores and Rocket cores, and if so, can you give an example of how to configure it?

Best Regards,

**Comment by jerryz123** [comment]
https://chipyard.readthedocs.io/en/stable/Customization/Heterogeneous-SoCs.html

**Comment by michael-etzkorn** [comment]
Jerry's link to Chipyad's documentation explains exactly how to build such a config. BOOM is not included within rocket-chip, so you'll need to either mimic how Chipyard includes BOOM in a fork of RC or use Chipyard.
