### ISSUE TITLE
CHIPYARD移植问题

### ISSUE THREAD

**Issue by zzzsssss1** [chipsalliance/rocket-chip#3290]
**Type of issue**: bug report | feature request | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown

**Development Phase**: request | proposal

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
chipyard 生成BOOM核能移植到VIVADO中，板子是XCZU15EG，但是显示的SCALA文件与板子本身不匹配
**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

**Comment by ZenithalHourlyRate** [comment]
Hi, this repo is rocket-chip, not chipyard/boom
