### ISSUE TITLE
How to remove L2 cache with Boom correctly ?

### ISSUE THREAD

**Issue by MJChku** [chipsalliance/rocket-chip#3382]
**Type of issue**: question

For the following boom config, what's the correct way to remove l2 cache ?
If I comment off new freechips.rocketchip.subsystem.WithInclusiveCache(nBanks=8, nWays=16, capacityKB=2048), the accelerator (protoacc) fails for some test at

    Assertion failed in TOP.TestHarness.dut.system.boom_tile.buffer.TLMonitor_3. ( using Verilator )

class ProtoMegaBoomBaseConfigNoAccel extends Config(
new chipyard.iobinders.WithUARTAdapter ++
new chipyard.iobinders.WithTieOffInterrupts ++
new chipyard.iobinders.WithBlackBoxSimMem ++
new chipyard.iobinders.WithTiedOffDebug ++
new chipyard.iobinders.WithSimSerial ++
new testchipip.WithTSI ++
new chipyard.config.WithBootROM ++
new chipyard.config.WithUART ++
new chipyard.config.WithL2TLBs(1024) ++
new freechips.rocketchip.subsystem.WithNoMMIOPort ++
new freechips.rocketchip.subsystem.WithNoSlavePort ++
new freechips.rocketchip.subsystem.WithInclusiveCache(nBanks=8, nWays=16, capacityKB=2048) ++
new WithExtMemIdBits(7) ++
new freechips.rocketchip.subsystem.WithNMemoryChannels(4) ++
new freechips.rocketchip.subsystem.WithNExtTopInterrupts(0) ++
new boom.common.WithBoomCommitLogPrintf ++
new boom.common.WithMegaBooms ++ // mega boom config
new boom.common.WithNBoomCores(1) ++
new freechips.rocketchip.subsystem.WithCoherentBusTopology ++
new freechips.rocketchip.system.BaseConfig)

**Comment by ZenithalHourlyRate** [comment]
Hi, you should open this issue in chipyard instead of here.
