### ISSUE TITLE
Used by uart in rocket

### ISSUE THREAD

**Issue by lh815283750** [chipsalliance/rocket-chip#3400]
Hello, I simulated rocket-chip on firesim, and created two Uartbriges in rocket-chip, but did not load relevant drivers after starting the operating system. Therefore, I want to know how to manipulate the newly created uart.

**Comment by ZenithalHourlyRate** [comment]
I assume firesim should be a more appropriate place to post this question.

**Comment by lh815283750** [comment]
Yes, thank you. I'm sorry I made a mistake
