### ISSUE TITLE
Rocket-chip emulator does not build /Make

### ISSUE THREAD

**Issue by sramichetty20019** [chipsalliance/rocket-chip#3484]
Hi all ,

I am new to rocket-chip, i have cloned the repository followed all the instructions to download and compile all the dependencies like riscv-tools,chisel,firrtl,verilator,yosys,expresso when i cd into the emulator directory and do make i get the following error .Another thing to mention is when i use sbt test with chisel some of the tests fail, same with firrtl..

this is the error i am getting 

~/rocket-chip/emulator$ make
cd /home/sramitchetty9/rocket-chip && mill rocketchip.assembly
/bin/bash: line 1: mill: command not found
make: *** [/home/sramitchetty9/rocket-chip/Makefrag:47: /home/sramitchetty9/rocket-chip/out/rocketchip/assembly.dest/out.jar] Error 127

please provide me with some information on how to resolve this

the issue i am getting when i use sbt test in firrtl directory is as follows:
```

[info] *** 90 TESTS FAILED ***
[error] Failed tests:
[error] 	firrtlTests.InlineAcrossCastsEquivalenceSpec
[error] 	firrtlTests.transforms.CombineCatsSpec
[error] 	firrtlTests.OpsConstantPropagationTest
[error] 	firrtl.backends.experimental.smt.end2end.AsyncResetSpec
[error] 	firrtl.backends.experimental.smt.end2end.EndToEndSMTSpec
[error] 	firrtl.backends.experimental.smt.end2end.UninterpretedModulesSpec
[error] 	firrtlTests.NegSpec
[error] 	firrtlTests.OpsLowFirrtlOptimizationTest
[error] 	firrtlTests.ConstantPropagationEquivalenceSpec
[error] 	firrtl.backends.experimental.smt.end2end.MemorySpec
[error] 	firrtlTests.OpsCommonSubexprEliminationTest
[error] 	firrtl.backends.experimental.smt.end2end.SMTCompilationTest
[error] 	firrtl.backends.experimental.rtlil.end2end.RtlilCompilationTest
[error] 	firrtl.backends.experimental.smt.end2end.AssertAssumeStopSpec
[error] 	firrtl.backends.experimental.rtlil.end2end.RtlilEquivalenceTest
[error] 	firrtlTests.InlineBooleanExpressionsSpec
[error] 	firrtlTests.OpsDeadCodeEliminationTest
[error] 	firrtlTests.VerilogEquivalenceSpec
[error] 	firrtl.backends.experimental.smt.end2end.UndefinedFirrtlSpec
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 133 s (02:13), completed Sep 16, 2023 5:05:40 PM
```

**Comment by n-kremeris** [comment]
Hi!
You need to install "mill", which is a tool for building scala code. See info here: [mill installation](https://mill-build.com/mill/Installation_IDE_Support.html)

**Comment by sramichetty20019** [comment]
Thank you , its working now
