### ISSUE TITLE
How to generate Boom core  on other FPGA platforms like zcu102

### ISSUE THREAD

**Issue by ProJeKTRED** [chipsalliance/rocket-chip#3524]
As a beginner, I have searched for other projects that generate Boom cores, but they are no longer available due to updates to the boom core and git loss. I only have zcu102 in our lab. Thank u.
https://github.com/li3tuo4/rc-fpga-zcu

**Comment by jerryz123** [comment]
Currently the supported mechanism is to add more FPGA board support to Chipyard. This question is best directed to the Chipyard repo, which supports BOOM. Rocket-chip is an independent project.

**Comment by ProJeKTRED** [comment]
> Currently the supported mechanism is to add more FPGA board support to Chipyard. This question is best directed to the Chipyard repo, which supports BOOM. Rocket-chip is an independent project.

ok, thanks for you reply. So i should submit issue in the feature request of chipyard?

**Comment by jerryz123** [comment]
Yes.
