### ISSUE TITLE
Executing c.fld on Rocket chip load the wrong value in the destination register

### ISSUE THREAD

**Issue by trambu** [chipsalliance/rocket-chip#3550]
**Type of issue**: bug report

**Impact**: unexpected behavior

**Development Phase**: request

**Other information**
 
Executing the `c.fld` instruction to load a double precision floating point returns `zero` instead of the actual value. On the Spike golden model, no error happens, and the load instruction updates the value of the register correctly. For more information, I attached a sequence of instructions and RISC-V binary to reproduce.

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
Execute following instructions on Rocket core:
```
c.fld   fs0, 0(s0)
lw       t0,0(s0)
```

First instruction will return `zero` but second instruction return actual value.

**What is the current behavior?**
Rocket core loads the wrong value in the destination register, i.e., in the `rd.`

Rocket core trace:
```
C0:       2926 [1] pc=[0000000080001048] W[r 2=00000000800223c0][1] R[r 2=00000000800223d0] R[r 0=0000000000000000] inst=[00001141] c.addi  sp, -16
C0:       2927 [1] pc=[000000008000104a] W[r 0=0000000000000000][0] R[r 2=00000000800223c0] R[r 8=0000000080022480] inst=[0000e422] c.sdsp  s0, 8(sp)
C0:       2928 [1] pc=[000000008000104c] W[r 8=00000000800223d0][1] R[r 2=00000000800223c0] R[r 0=0000000000000000] inst=[00000800] c.addi4spn s0, sp, 16
C0:       2929 [1] pc=[000000008000104e] W[r 8=0000000000000000][0] R[r 8=00000000800223d0] R[r 0=0000000000000000] inst=[00002000] c.fld   fs0, 0(s0)
C0:       2930 [1] pc=[0000000080001050] W[r 5=ffffffff80022460][1] R[r 8=00000000800223d0] R[r 0=0000000000000000] inst=[00042283] lw      t0, 0(s0)
C0:       2931 [1] pc=[0000000080001054] W[r15=0000000000000000][1] R[r 0=0000000000000000] R[r 0=0000000000000000] inst=[00004781] c.li    a5, 0
```

**What is the expected behavior?**
Rocket core has to load the content of the memory.

Spike trace:
```
core   0: 0x0000000080001048 (0x00001141) c.addi  sp, -16
core   0: 3 0x0000000080001048 (0x1141) x2  0x00000000800223c0
core   0: 0x000000008000104a (0x0000e422) c.sdsp  s0, 8(sp)
core   0: 3 0x000000008000104a (0xe422) mem 0x00000000800223c8 0x0000000080022480
core   0: 0x000000008000104c (0x00000800) c.addi4spn s0, sp, 16
core   0: 3 0x000000008000104c (0x0800) x8  0x00000000800223d0
core   0: 0x000000008000104e (0x00002000) c.fld   fs0, 0(s0)
core   0: 3 0x000000008000104e (0x2000) f8  0x0000000080022460 mem 0x00000000800223d0
core   0: 0x0000000080001050 (0x00042283) lw      t0, 0(s0)
core   0: 3 0x0000000080001050 (0x00042283) x5  0xffffffff80022460 mem 0x00000000800223d0
core   0: 0x0000000080001054 (0x00004781) c.li    a5, 0
core   0: 3 0x0000000080001054 (0x4781) x15 0x0000000000000000
```

**Please tell us about your environment:**

    - version: `RocketChip v1.6`
    - OS: `CentOS Linux release 7.9.2009 kernel: 5.15.0-78-generic`
    - Simulator: `VCS_2021.09-SP1`
    - Spike version: `1.1.1-dev`

[rc_test.riscv.zip](https://github.com/chipsalliance/rocket-chip/files/13830241/rc_test.riscv.zip)

**Comment by jerryz123** [comment]
The printed log does not display the matching written-back data for instructions which write back after the WB. This includes long latency instructions like integer div/rem.
