### ISSUE TITLE
REMU `x` by zero on the Rocket chip writes `0x0` to `rd` instead of `x`

### ISSUE THREAD

**Issue by trambu** [chipsalliance/rocket-chip#3552]
**Type of issue**: bug report

**Impact**: unexpected behavior

**Development Phase**: request

**Other information**
 
Executing the `remu    a3, a4, zero` instruction, Rocket chip writes `0x0` to `rd`, but based on specification, it has to write `a4` to `rd`. For more information, I attached a sequence of instructions and RISC-V binary to reproduce.

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
Execute following instructions on Rocket core:
```
remu    a3, a4, zero
```

The first instruction will return `zero` but a remu by zero has to return `a4`.

**What is the current behavior?**
Rocket core returns `0x0` instead of `0x84`.

Rocket core trace:
```
C0:       3195 [1] pc=[00000000800018d0] W[r15=0000000000000000][1] R[r 8=0000000080022400] R[r 0=0000000000000000] inst=[ec446783] lwu     a5, -316(s0)
C0:       3196 [1] pc=[00000000800018d4] W[r14=0000000000000084][1] R[r 8=0000000080022400] R[r 0=0000000000000000] inst=[ec843703] ld      a4, -312(s0)
C0:       3198 [1] pc=[00000000800018d8] W[r13=0000000000000000][0] R[r14=0000000000000084] R[r15=0000000000000000] inst=[02f776b3] remu    a3, a4, a5
C0:       3199 [1] pc=[00000000800018dc] W[r15=0000000000000000][1] R[r 8=0000000080022400] R[r 0=0000000000000000] inst=[fec42783] lw      a5, -20(s0)
C0:       3201 [1] pc=[00000000800018e0] W[r14=0000000000000001][1] R[r15=0000000000000000] R[r 0=0000000000000000] inst=[0017871b] addiw   a4, a5, 1
```

**What is the expected behavior?**
Rocket core has to return `0x84`.

Spike trace:
```
core   0: 0x00000000800018d0 (0xec446783) lwu     a5, -316(s0)
core   0: 3 0x00000000800018d0 (0xec446783) x15 0x0000000000000000 mem 0x00000000800222c4
core   0: 0x00000000800018d4 (0xec843703) ld      a4, -312(s0)
core   0: 3 0x00000000800018d4 (0xec843703) x14 0x0000000000000084 mem 0x00000000800222c8
core   0: 0x00000000800018d8 (0x02f776b3) remu    a3, a4, a5
core   0: 3 0x00000000800018d8 (0x02f776b3) x13 0x0000000000000084
core   0: 0x00000000800018dc (0xfec42783) lw      a5, -20(s0)
core   0: 3 0x00000000800018dc (0xfec42783) x15 0x0000000000000000 mem 0x00000000800223ec
core   0: 0x00000000800018e0 (0x0017871b) addiw   a4, a5, 1
core   0: 3 0x00000000800018e0 (0x0017871b) x14 0x0000000000000001
```

**Please tell us about your environment:**

    - version: `RocketChip v1.6`
    - OS: `CentOS Linux release 7.9.2009 kernel: 5.15.0-78-generic`
    - Simulator: `VCS_2021.09-SP1`
    - Spike version: `1.1.1-dev`

**Comment by jerryz123** [comment]
The printed log does not display the matching written-back data for instructions which write back after the WB. This includes long latency instructions like integer div/rem.
