### ISSUE TITLE
Mill resolve error

### ISSUE THREAD

**Issue by srishti-sr** [chipsalliance/rocket-chip#3618]
I am trying to run the rocket-chip code using nix environment but i am getting these errors.Further in intellij ide i am getting a problem in executing bsp and facing this error:
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it. And the following error trying to run rocketchip code:
arushisharma@Arushis-MacBook-Air ~ % nix-shell -p cowsay lolcat

[nix-shell:~]$ cd rocket-chip

[nix-shell:~/rocket-chip]$ mill rocket-chip
No mill version specified.
You should provide a version via '.mill-version' file or --mill-version option.
Using mill version 0.11.7
[[build.sc](http://build.sc/)] [47/53] zincReportCachedProblems 
Cannot resolve rocket-chip. Did you mean rocketchip?

[nix-shell:~/rocket-chip]$ mi;; rocketchip
bash: syntax error near unexpected token `;;'

[nix-shell:~/rocket-chip]$ mill rocketchip
No mill version specified.
You should provide a version via '.mill-version' file or --mill-version option.
Using mill version 0.11.7
[[build.sc](http://build.sc/)] [47/53] zincReportCachedProblems 
Cannot find default task to evaluate for module rocketchip

I am using MacOS apple chip,mill version:11.0.7 and nix installed version:2.21.0.

**Comment by sequencer** [comment]
The Rocket Chip currently uses nix to configure the build and/or development environment, you need to install it first depending on your OS distro.
