### ISSUE TITLE
Rocket updates sepc and stval in M mode

### ISSUE THREAD

**Issue by zhangkanqi** [chipsalliance/rocket-chip#3629]
**Type of issue**: bug report

**Development Phase**: proposal

**Other information: **
**What is the current behavior?**
When encounter an exception at pc `0x0000000000002a70` in  M mode, Rocket updates sepc and stval.
![image](https://github.com/chipsalliance/rocket-chip/assets/34207592/4b5442aa-78a3-4a16-a58c-9c5760ad0061)

**What is the expected behavior?**
Don't update sepc and stval, only update mepc and mtval.

**Please tell us about your environment:**
    - chipyard version:  `b7644b2455cc4bae190e811a5d8085f3aad85b87`
    - Rocket version:  `47f7b7144727f0340d511d35b9f6c7a91b2a276f`

**What is the use case for changing the behavior?**
For debug and reproduce: https://github.com/zhangkanqi/mismatch/blob/main/id_10.zip

**Comment by jerryz123** [comment]
The waveform you depict shows the correct behavior. A trap is taken into S-mode, so sepc and stval are updated.
