### ISSUE TITLE
Steps to assemble and execute a riscv assembly file

### ISSUE THREAD

**Issue by gituserdeepika** [chipsalliance/rocket-chip#3668]
I am trying to analyze if I can stream data from memory to the Rocket CPU. But by using a C based test (https://chipyard.readthedocs.io/en/latest/Software/Baremetal.html) there is a lot of assembly code that is created due to which I am not able to do this analysis. So I prefer to write my tests natively in assembly right now for my analysis. I do not want stack etc. for now, just want to write an assembly based test, assemble the same and make Rocket execute only that. Can someone provide the steps for the same?

**Comment by jerryz123** [comment]
There is plenty of existing online documentation on how to compile assembly into an ELF file that can be run in RISC-V ISA simulators or RTL simulators.
