### ISSUE TITLE
Creating 32 bit rocket-chip without fpu

### ISSUE THREAD

**Issue by gituserdeepika** [chipsalliance/rocket-chip#3669]
Hi,
I am able to simulate the 64 bit rocketchip via the chipyard flow. Please let me know how to create and simulate a 32 bit core without fpu.
Thanks

**Comment by gituserdeepika** [comment]
There is no Configs.scala under rocketchip/src/main/scala/rocket directory.
However, under chipyard/generators/rocket-chip/src/main/scala/subsystem directory I see a Configs.scala which has a config class for With1TinyCore. This is something I want to generate and run. Can you please provide the steps to use this config.

**Comment by jerryz123** [comment]
Please follow the chipyard instructions for building RTL of custom configurations
