### ISSUE TITLE
I+D cache must handle TileLink errors sensibly

### ISSUE THREAD

**Issue by terpstra** [chipsalliance/rocket-chip#472]
When a TileLink device reports error (none currently do this other than AXI bridge) to the Icache, the processor should probably fault. Similarly, the data cache should do something sensible. Loads can probably be precise faults, but can stores also?

We need to specify what is the desired behaviour and then implement it.

**Comment by hcook** [comment]
DCache handled in #994

**Comment by aswaterman** [comment]
ICache was handled a long time ago, too
