### ISSUE TITLE
Address Map error

### ISSUE THREAD

**Issue by MarcoGeuna** [chipsalliance/rocket-chip#713]
Hi all!

I'm trying to change the address map of my Rocket Chip instance. In particular, my interest is trying to **change the address space of the main memory** from 0x800000000 - 0x90000000 to something else.  In particular, I changed the base address into 0xb0000000 and then 0x40000000.

Up to now, I **tried to modify the value _base_** inside [MasterConfig ExtMem](https://github.com/ucb-bar/rocket-chip/blob/master/src/main/scala/rocketchip/Configs.scala#L42), but when I try to simulate using Verilator, then I obtain this error message inside the .out file:
> 
> terminate called after throwing an instance of 'std::runtime_error'
>                    what():  bad syscall #2147487744

I think that **probably I have to modify also something else**, if I want to change the address space of the memory, but **I don't know what!** So, any help is really appreciated!

Thank you all!

PS: I forgot to say that I'm not using the latest version of Rocket Chip. Mine is the following:
commit b2ee5e7d384febd087ded8a2995fda83d8d9cec0  2017-01-31, 17:16, Author: Wesley W. Terpstra

**Comment by sequencer** [comment]
No enough information to reproduce this issue, closing.
But basically is that we need documentation on diplomatic SoC components.
