### ISSUE TITLE
Tilelink and AXI

### ISSUE THREAD

**Issue by ViccoYang** [chipsalliance/rocket-chip#717]
I studied this repo and the project-template. There is a MMIO  peripheral device example PWM in project template, but I saw both tilelink and AXI version in PWM.scala, so I'm confused the difference of these two version and I'm not sure where should the device be in this pic:
![rocket](https://cloud.githubusercontent.com/assets/21357520/25606548/96d8f912-2f44-11e7-926e-d74772c770fc.PNG)
I think the AXI version of PWM should be at "AHB&APB Peripherals", but what about the tilelink version?
Thanks for your help!

**Comment by terpstra** [comment]
There is no PWM in rocketchip? If you have a TL device, you probably want to connect it off the periphery bus, not the memory bus shown in your diagram.

**Comment by muhammadali201** [comment]
is there any example of connecting AXI4 based peripherals with rocket-chip

**Comment by sequencer** [comment]
See repo in https://github.com/sifive/sifive-blocks
But we need a test case to illustrate how to add new SoC devices.
